### ISSUE TITLE
SES problem with Send Email

### ISSUE THREAD

**Issue by BrUn3y** [aws/aws-sdk-php-laravel#100]
I try to send email but i have this problems with 
![captura de pantalla 2016-06-08 a las 5 16 51 p m](https://cloud.githubusercontent.com/assets/6274023/15912913/cba4bf78-2d9c-11e6-8a1d-e1ea651d7629.png)
![captura de pantalla 2016-06-08 a las 5 17 07 p m](https://cloud.githubusercontent.com/assets/6274023/15912916/cf087416-2d9c-11e6-8f38-ef8bc22299b2.png)

I belive my configuration is correct, the sdk run in laravel 5.1

Composer.json
`    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "aws/aws-sdk-php-laravel": "~3.0",
        "guzzlehttp/guzzle": "~5.3|~6.0"
    }`

app.php
![captura de pantalla 2016-06-08 a las 5 20 28 p m](https://cloud.githubusercontent.com/assets/6274023/15912986/44e1bc10-2d9d-11e6-94d6-55c728628d2e.png)
![captura de pantalla 2016-06-08 a las 5 20 39 p m](https://cloud.githubusercontent.com/assets/6274023/15912989/4635e1c2-2d9d-11e6-820b-18abbd14d182.png)

aws.php
![captura de pantalla 2016-06-08 a las 5 21 52 p m](https://cloud.githubusercontent.com/assets/6274023/15913025/72f96e72-2d9d-11e6-81e5-992688d57fe6.png)

In this controller i use for send email an the execute the services AWS
![captura de pantalla 2016-06-08 a las 5 23 41 p m](https://cloud.githubusercontent.com/assets/6274023/15913123/d11f6948-2d9d-11e6-94fa-21df876a73a8.png)

**Comment by cjyclaire** [comment]
@BrUn3y , according to the Error Message, it might have to do with [credential](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html) issues. Could you provide more information? e.g. Are those error messages show up every time? In the `aws.php` file, I see `env(AWS_REGION, us-east-1)`, may I ask why are you sourcing from environment instead of passing in "us-east-1" directly?

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen it if you have further questions! :)

**Comment by Jameron** [comment]
The region should be sourced via env() rather than passed directly in.
