### ISSUE TITLE
Small caveat with env variables

### ISSUE THREAD

**Issue by jbardnz** [aws/aws-sdk-php-laravel#101]
Hey guys,

Following the readme I have the default env variables set and was setting the package read them automatically:

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=ap-southeast-2

I ran into an issue when I started using laravel config:cache - the package then can't read env variables and the package can't Auth with AWS unless you specifically set the values in the config file. 

I think it could be worth putting a disclaimer in the readme or possibly always setting the config variables.

**Comment by cjyclaire** [comment]
@jbardnz thank you for your feedback, are you suggesting the [`Configuration`](https://github.com/aws/aws-sdk-php-laravel#configuration) description here? Could you provide more information about what "caveat"behavior  that you might like to see? 
Also, may I ask why you would like to see that? Since it's true for SDK default credential behavior to fetch credentials from environment variable first.

**Comment by jbardnz** [comment]
Hello,

Yes I was talking about an update to the configuration update. If you look at the [upgrade notes for Laravel 5.2 ](https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0)you will see this section:

> If you are using the config:cache command during deployment, you must make sure that you are only calling the env function from within your configuration files, and not from anywhere else in your application.
> 
> If you are calling env from within your application, it is strongly recommended you add proper configuration values to your configuration files and call env from that location instead, allowing you to convert your env calls to config calls.

So if you are following Laravel best practice it would be good to enforce users to always use the config file instead of only setting env variables.

**Comment by cjyclaire** [comment]
@jbardnz Thanks for the information, good to know. 

To provide more information on the SDK side, there is a [default](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html) credential chain in SDK that fetch env value before profile, this is a behavior shared across all AWS SDKs, I think it might cause more confusion if changing the logic there. Yet, adding more information about this issue in `README.md` makes great sense to me.
Does this sounds good to you? I'll open a PR soon with more documentation on that.

**Comment by jbardnz** [comment]
Hey

Yes that sounds like a good solution. Just simple documentation letting users know they must add the credentials into the config file if they use php artisan config:cache.

**Comment by cjyclaire** [comment]
I'll leave PR open while closing this, yet feel free to reopen if you have further comments :)
