### ISSUE TITLE
guzzlehttp/guzzle

### ISSUE THREAD

**Issue by douglasmiguel** [aws/aws-sdk-php-laravel#103]
Hi, I'm using the package on Laravel 4.2 and when I do the composer update I get this following message:
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

Can you please update the package composer?

Thanks a lot.

**Comment by cjyclaire** [comment]
May I ask the Sdk version being used? You need to use aws sdk PHP v3.

**Comment by douglasmiguel** [comment]
I'm using "aws/aws-sdk-php-laravel": "1.*",

The v3 is not only Laravel 5?

**Comment by cjyclaire** [comment]
@douglasmiguel Apology for replying late, I'm suggesting `aws-sdk-php` [v3](https://github.com/aws/aws-sdk-php-laravel/blob/master/composer.json#L16), it's dependency in `composer.json` already. Could you double check the `aws-sdk-php` version being used?

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen if you have further comments :)
