### ISSUE TITLE
Class 'Aws\Common\Aws' not found when update composer

### ISSUE THREAD

**Issue by ricardofontanelli** [aws/aws-sdk-php-laravel#106]
Hello,

We were using Laravel 4.2 with aws/aws-sdk-php-laravel 1.1.2, today after we updated composer, it download a new version of aws/aws-sdk-php-laravel (1.2.0) and updated too the aws/aws-sdk-php from 2.8.31 to 3.19.6, and now we have this error Class 'Aws\Common\Aws'.

I think the correct version of aws/aws-sdk-php to be used in aws/aws-sdk-php-laravel 1.2.0 composer.json is 2.* (or 2.8.*) and not ~3.0 like is it now.

Can I open a PR?

Tks,

**Comment by cjyclaire** [comment]
@ricardofontanelli Thanks for reporting, it looks like breaking, I'll revert the change and fix that.

**Comment by cjyclaire** [comment]
Fixed, closing
