### ISSUE TITLE
Set custom URL

### ISSUE THREAD

**Issue by praditha** [aws/aws-sdk-php-laravel#109]
Hello,
I'm sorry if this question is out of scope.

Currently I'm using Laravel 5.2 and the latest version of aws-sdk-php-laravel.
But I'm not using S3 from AWS, I use [CEPH](http://ceph.com/ceph-storage/) as my storage.

Based on this [tutorial](http://docs.ceph.com/docs/jewel/radosgw/s3/php/), I can use aws sdk to connect to my storage, but on that tutorial, it still use the SDK version 1. On that version we can see the base URL can be changed ( `$Connection->set_hostname($HOST);` ).
But I have no idea how to change it on laravel, because the config is only like this:
```php
's3' => [
            'driver' => 's3',
            'key' => env('S3_KEY'),
            'secret' => env('S3_SECRET'),
            'region' => env('S3_REGION'),
            'bucket' => env('S3_BUCKET'),
        ],
```

and by default the base URL is `https://s3.us.amazonaws.com/[bucket path]`

can you guys please help me how to change the base URL..?

Thanks.

**Comment by cjyclaire** [comment]
Closing since it's a duplicate issue :)
