### ISSUE TITLE
credentials?

### ISSUE THREAD

**Issue by wyklif** [aws/aws-sdk-php-laravel#111]
hello, i am using laravel 5.3 however i see no credentials settings in the config file my config file looks like this

```
<?php

use Aws\Laravel\AwsServiceProvider;

return [

    /*
    |--------------------------------------------------------------------------
    | AWS SDK Configuration
    |--------------------------------------------------------------------------
    |
    | The configuration options set in this file will be passed directly to the
    | `Aws\Sdk` object, from which all client objects are created. The minimum
    | required options are declared here, but the full set of possible options
    | are documented at:
    | http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html
    |
    */

    'region' => env('AWS_REGION', 'us-east-1'),
    'version' => 'latest',
    'ua_append' => [
        'L5MOD/' . AwsServiceProvider::VERSION,
    ],
];
```

**Comment by jeskew** [comment]
Hi @wyklif,

The `credentials` property is omitted from the default config file to allow for applications to use credentials sourced from environment variables, a credentials file, or the EC2/ECS instance metadata service. You can add credentials to the config file as described in this repository's README if you would prefer to manage them in that way, but I would recommend taking a look at [our developer guide](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html) before using hard-coded credentials.

Hope that helps! Please feel free to reopen if you have any questions or concerns.

**Comment by wyklif** [comment]
got past it thanks but how do i upload a publicly accesible file do i just include the 'ACL'    => 'public-read', i am using the laravel 5 service provider
