### ISSUE TITLE
Support for AWS Instance and ECS Role Credentials

### ISSUE THREAD

**Issue by brianwhigham** [aws/aws-sdk-php-laravel#112]
We would like to use ECS task roles to authenticate to AWS.  This allows us to avoid putting yet another secret in our config files.  In fact, it allows us to store all secrets in S3 and make them accessible using task roles.  Plus, S3 can securely version our config files for us.  Using instance roles is a next best option; but, task roles take the cake with ECS/docker.

From the doc at http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html: `Using IAM roles is the preferred technique for providing credentials to applications running on Amazon EC2.`

The task role IAM credentials can be found at http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI

The output looks like this:

  ```
{
  "RoleArn": "arn:aws:iam::079393838737363:role/some-role-name",
  "AccessKeyId": "ASDFSKJLWENDKILDSKFJ",
  "SecretAccessKey": "LKJEKJDSLFKDSJFELWKJFWELDFKJSDLFK",
  "Token": "dlkasjdhfe3iudjfKJ22342mnsDKJFSKDHUWEKSJDFHSKHDSFKJSHDFKSJDHFKSDJHFKSJDHFLKSDJHFSDKJFHSDLKJFGSDFJHSDFHGIDWUWHFSDIHJFWKLJHFDSFKJh32342342345235235235/sdslkfjsdlfkjsdf234234234SDFSDFSDFSDFSDoP5kkcV91heXNix8c0CwtI8Hv2TpVkwhw8zU4FUSqQMsAp1pV5bh2iUjcDjbbrM4197ATydI/e+xSl7Gn0QA21Q4yf3ma7XSxXD2QBjSYW3dtSQxhpHJ0iEnWBUaDydolcGtAYa03oj/TOZ7ec1Gi2cCUjgFdrSfs/14oz4rVwwU=",
  "Expiration": "2017-01-11T02:34:23Z"
}
```

Thanks

**Comment by jeskew** [comment]
Hi @brianwhigham,

The AWS SDK for PHP will automatically use an ECS task role if the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable is set and no hard-coded credentials are provided. If you do not include an access key and secret in your application config, the SDK will retrieve credentials from the environment on which it is being run. Please consult [the SDK developer guide](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html) for a more in-depth explanation of how the default credential loader works, and please feel free to reopen this issue if you have any questions or concerns.
