### ISSUE TITLE
Is this compatible with Laravel 5.4?

### ISSUE THREAD

**Issue by kiwo12345** [aws/aws-sdk-php-laravel#113]
I just wonder if this is compatible with Laravel 5.4?

**Comment by GrahamCampbell** [comment]
Try it out.

**Comment by robmpreston** [comment]
Graham as helpful as usual.

**Comment by jeskew** [comment]
Yes, it is. I encountered no issues installing this service provider in a new Laravel 5.4 application and doing some basic testing. If you do run into any specific issues when using this package with Laravel 5.4, please let us know!

**Comment by avinashi37** [comment]
Hi @jeskew ,

Yes, I have the issue when I tried to use it in laravel 5.4. The steps I followed are as below:

1. Done setup as per the instruction given in document.
2. Tried to upload mp3 audio file using code below :

$s3 = AwsFacade::createClient('s3');
        
        $result = $s3->putObject(array(
            'Bucket'     => 'luxeradio',
            'Content-Type' => 'audio/mpeg',
            'Key'        => $fileName,
            'SourceFile' => $url,
        ));

But I get the time-out exception when tried to upload file.

below is the aws.php file in config directory 

<?php

use Aws\Laravel\AwsServiceProvider;

return [

    /*
    |--------------------------------------------------------------------------
    | AWS SDK Configuration
    |--------------------------------------------------------------------------
    |
    | The configuration options set in this file will be passed directly to the
    | `Aws\Sdk` object, from which all client objects are created. The minimum
    | required options are declared here, but the full set of possible options
    | are documented at:
    | http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html
    |
    */
    'credentials' => [
        'key'    => '<key>',
        'secret' => '<secret>',
    ],
    'region' => env('AWS_REGION', 'us-east-1'),
    'version' => 'latest',
    'ua_append' => [
        'L5MOD/' . AwsServiceProvider::VERSION,
    ],
];

- one more question about region selection. Is it server region or the region we are selecting in bucket.

Please help! I tried several times by applying different changes and googling but no luck.  :(
