### ISSUE TITLE
Class 'Aws\Laravel\AwsServiceProvider' not found  after update laravel

### ISSUE THREAD

**Issue by neoacevedo** [aws/aws-sdk-php-laravel#115]
Hi. Currently I am using Laravel 4.2 but in my needings I am updating it to latest version. Doing the first step, when I run _php composer.phar update_ or _php artisan --version_ I get the following error:

`Class 'Aws\Laravel\AwsServiceProvider' not found in  (...)/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 150`

Previously I ran _php composer.phar update_ to install all my project dependences and configuring app.php with providers and aliases. Just after that, with above commands I am getting those errors.

Is there some about I have forgotten?

**Comment by renepardon** [comment]
I've the same problem with laravel 5.4:

from my composer.json:

> "aws/aws-sdk-php-laravel": "^3.1",
> "laravel/framework": "5.4.*",

I've deleted the bootstrap/cache/services.php file and vendor directory, did a composer install/update and now I constantly receive this error 

> Class 'Aws\Laravel\AwsServiceProvider' not found

**Comment by renepardon** [comment]
Problem starts when adding AwsServiceProvider to the app.php config file.

**Comment by fattchris** [comment]
Same problem here with Lumen 5.1 - any updates?

**Comment by N7snake** [comment]
Same problem here, in my case with Laravel 5.3.

**Comment by renepardon** [comment]
I bought (for monthly rental) a custom storage which I mount to my servers because with this package I can't work right now ;(
Hopefully I find some time to help you fixing this but right now it's not possible for me.

**Comment by kstich** [comment]
Did everyone with this problem upgrade in place from a previous version? If so, can you please provide what versions of Laravel, Laravel-SDK wrapper, and the SDK you started with and what versions you upgraded to?

**Comment by scgeorge** [comment]
Follow the instructions here https://github.com/aws/aws-sdk-php-laravel . All that is needed are the Installation then Laravel specific modification (unless you need to modify your aws.php).

**Comment by seanramey82** [comment]
Same issue on laravel 5.5, started with package version 3.48. Any update on this?

**Comment by fhreza** [comment]
Same problem here, I'm using Laravel 5.5 and for the first time using AWS SDK 3.48.6

**Comment by insign** [comment]
Auto discover only worked here using dev-master in composer

**Comment by ahsanmahmood** [comment]
any solution???
