### ISSUE TITLE
Receiving 403 forbidden error

### ISSUE THREAD

**Issue by anthonyPlexuss** [aws/aws-sdk-php-laravel#117]
Recently, I started to move my old Laravel 4.2 code to 5.4 . I have copied the aws upload file that I had, and currently I'm getting  the following error:

`Error executing "PutObject" on "https://s3-us-west-2.amazonaws.com/asset.secret.com%2Fusers%2Fdocs/sample_passport_2017_06_27_21_57_57.png"; AWS HTTP error: Client error: PUT https://s3-us-west-2.amazonaws.com/asset.secret.com%2Fusers%2Fdocs/sample_passport_2017_06_27_21_57_57.png resulted in a 403 Forbidden response:`

Here's my code : 

`$s3 = AWS::createClient('s3');`
		`$s3->putObject(array(`
		         `'ACL' => 'public-read',`
			`'Bucket' => $bucket_url,`
			`'Key' => $saveas,`
			`'SourceFile' => $path`
		`));`
where bucket_url is 

asset.secret.com/users/docs

for some reason the bucket_url is getting urlencoded, and I think that's the issue, does anyone has the same issue?

**Comment by kstich** [comment]
Are you certain the name of the 'Bucket' has the '/' characters in it? I believe the bucket name for this case would be `'asset.secret.com'` and the `'users/docs/'` would appear at the front of the 'Key' (your `$saveas`).

**Comment by omar-faruk-sust** [comment]
I am also having the same issue. I am certain about my file path.

**Comment by anthonyPlexuss** [comment]
Hi Omar,

I found a solution last year, using the following, hope it helps you too.

my package versions are as follow:

"aws/aws-sdk-php": "^3.48",
"aws/aws-sdk-php-laravel": "~3.0",

`$bucket_url = "users/docs";`
`$saveas = "filename.jpg";`
`$path = "path to your file";`

`$s3->putObject(array(
			'ACL' => 'public-read',
			'Bucket' => 'asset.secret.com',
			'Key' => $bucket_url . '/' . $saveas,
			'SourceFile' => $path,
		));`
