### ISSUE TITLE
Creating a new instance client

### ISSUE THREAD

**Issue by lorenzoaiello** [aws/aws-sdk-php-laravel#118]
How can I create a new client in a controller using credentials provided within that controller that differ from those in the .env?

**Comment by csoseman** [comment]
Try using PHP's `putenv` function to override the defaults in `.env`. Example:

http://php.net/manual/en/function.putenv.php

```php
putenv('AWS_ACCESS_KEY_ID=ABCDEF1234456789');
putenv('AWS_SECRET_ACCESS_KEY=TH1SISMy$eCr3tKey');

// Whatever you want to call would go here
$ec2 = \AWS::createClient('iam');
$results = $ec2->getAccountSummary();
```

The AWS PHP SDK uses `getenv` to retrieve your credentials and using `putenv` function will override this at runtime.

**Comment by lorenzoaiello** [comment]
Thanks, that did the trick.
