### ISSUE TITLE
The request signature we calculated does not match the signature you provi ded.Check your Secret Access Key and signing method

### ISSUE THREAD

**Issue by smartyaunt** [aws/aws-sdk-php-laravel#120]
$this->disk = app()->make('aws')->createClient('s3', [
            'endpoint'=> 'http://api.storebox.vn/',
 ]);

dd($this->disk->listBuckets([]))

and my config/aws.php  key and secret is right  but when get blow error

The request signature we calculated does not match the signature you provi
ded.Check your Secret Access Key and signing method

**Comment by kstich** [comment]
This is almost certainly an issue either the content of the secret access key you have set or the [layout of your credentials configuration](https://github.com/aws/aws-sdk-php-laravel#configuration). Can you supply a copy of your `app/config/aws.php` file with your credentials removed?

**Comment by jamiejones85** [comment]
I'm also having this issue after upgrading L5.0 to 5.1.

composer.json
```
"require": {
        "laravel/framework": "5.1.*",
        "aws/aws-sdk-php-laravel": "3.0.*",
..
```

aws.php
```
return [
    'region' => env('AWS_REGION', 'eu-west-1'),
    'version' => 'latest',
    'ua_append' => [
        'L5MOD/' . AwsServiceProvider::VERSION,
    ],
];
```
.env
```
AWS_ACCESS_KEY_ID=A........Q
AWS_SECRET_ACCESS_KEY=b...............................3
AWS_REGION=eu-west-1
```

Thanks

**Comment by kstich** [comment]
@jamiejones85 Is `'.env'` a file? The AWS SDK for PHP loads [from environment variables](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html#environment-credentials). It also supports using [specific ini formatted credentials files](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html#credential-profiles).

**Comment by jamiejones85** [comment]
Laravel uses https://github.com/vlucas/phpdotenv to load .env in to environment variables. It worked fine on an older version with Laravel 5, but stops with 5.1. 

I get "The request signature we calculated does not match the signature you provided.Check your Secret Access Key and signing method" when doing a PutObject

**Comment by commanderZiltoid** [comment]
Also receiving this message.

```
return [

    /*
    |--------------------------------------------------------------------------
    | AWS SDK Configuration
    |--------------------------------------------------------------------------
    |
    | The configuration options set in this file will be passed directly to the
    | `Aws\Sdk` object, from which all client objects are created. The minimum
    | required options are declared here, but the full set of possible options
    | are documented at:
    | http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html
    |
    */
    'credentials' => [
        'key'    => 'correct_key_id',
        'secret' => 'correct_key_secret',
    ],
    'region' => env('AWS_REGION', 'us-east-2'),
    'version' => 'latest',
    'ua_append' => [
        'L5MOD/' . AwsServiceProvider::VERSION,
    ],
];
```

**Comment by ranganathabrr** [comment]
With out AWS access key & secrect AWS services not working(IAM Role associated)

It was working with out security credentials, I did composer update, and its updated new PHP SDK version. My AWS services stop working, If i provide security credentials its start working.

Ec2 instance associated with IAM Role, I don't want to expose security credentials.

And the config file:

```
<?php

use Aws\Laravel\AwsServiceProvider;

return [
    'region' => env('AWS_SNS_REGION'),
    'version' => 'latest',
    'ua_append' => [
        'L5MOD/' . AwsServiceProvider::VERSION,
    ],
];
```

**Comment by samlin86** [comment]
@ranganathabrr I found another issue #148 and the response 8 days ago stating that release 3.3.1 fixes this. It solved the issue for me as well when I updated to this version.

**Comment by howardlopez** [comment]
Thanks for letting us know. I believe ranganathabrr was involved in #148 as well, and it looks like the issues here should also be resolved with the latest updates.
