### ISSUE TITLE
How can i upload the image using url?

### ISSUE THREAD

**Issue by ssboopathi1991** [aws/aws-sdk-php-laravel#121]
I am using laravel v5.2 I have installed the aws package. 

config/aws.php

    use Aws\Laravel\AwsServiceProvider;
    return [
        'credentials' => [
            'key'    => 'key',//I have used my key
            'secret' => 'secret',//I have used my secret
        ],
        'region' => 'eu-west-1',
        'version' => 'latest',
        // You can override settings for specific services
        'Ses' => [
            'region' => 'us-east-1',
        ],
    ];

/* Now I have tried uploading the image using image URL */

    $s3->putObject(array(
        'Bucket'     => 'bucket',
        'Key'        => 'destination path',
        'SourceFile' => 'i will provide the image url',
        'ACL'        => 'public-read',
    ));

/* Final response */

CouldNotCreateChecksumException in SignatureV4.php line 160:

**A sha256 checksum could not be calculated for the provided upload body, because it was not seekable. To prevent this error you can either 1) include the ContentMD5 or ContentSHA256 parameters with your request, 2) use a seekable stream for the body, or 3) wrap the non-seekable stream in a GuzzleHttp\Psr7\CachingStream object. You should be careful though and remember that the CachingStream utilizes PHP temp streams. This means that the stream will be temporarily stored on the local disk.**

**Comment by kstich** [comment]
The [documentation for `putObject` states that `'SourceFile'` is 'The path to a file on disk to use instead of the Body parameter'](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobject). You'll need to either get a local copy of that image or build a seekable stream to it for passing to the `'Body'` parameter.
