### ISSUE TITLE
How I can change server

### ISSUE THREAD

**Issue by opi-dopi** [aws/aws-sdk-php-laravel#124]
How can I change the server. I need to request batset data from one server and create baketas on another server.
Like this 
```
`$credentials = new Aws\Credentials\Credentials(ACCESS_KEY_ID, SECRET_ACCESS_KEY);

$s3 = new Aws\S3\S3Client([
    'version'     => 'latest',
    'region'      => 'us-east-1',
    'credentials' => $credentials
]);`
```

**Comment by kstich** [comment]
To use multiple regions, you can either create two S3Client objects (one for each region) or use the [S3MultiRegionClient](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-multiregion-client.html).

Note: Your credentials are private information and should not be shared in any way.
