### ISSUE TITLE
authorizeSecurityGroupIngress Description doesn't work

### ISSUE THREAD

**Issue by captn3m0** [aws/aws-sdk-php-laravel#125]
We're trying to set a description while creating a SecurityGroup Ingress Rule. As per the docs, this should work:

```php
<?php

$data = 
array (
  'DryRun' => false,
  'GroupId' => 'sg-123456',
  'IpPermissions' => 
  array (
    0 => 
    array (
      'FromPort' => '123',
      'IpProtocol' => 'tcp',
      'ToPort' => '123',
      'IpRanges' => 
      array (
        0 => 
        array (
          'CidrIp' => '127.0.0.1/32',
          'Description' => 'hello',
        ),
      ),
    ),
  ),
)

$ec2->authorizeSecurityGroupIngress([
    'DryRun'     => false,
    'GroupId'    => $lease['group_id'],
    'IpPermissions' => $permissions
]); 
```

We get a successful response, and the rule is created, but the Description is not applied to the rule.

**Comment by kstich** [comment]
You should be able to find the description in one of the places mentioned [in this blog post.](https://aws.amazon.com/blogs/aws/new-descriptions-for-security-group-rules/) Please also make sure your [API request parameters match the documentation.](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-ec2-2016-11-15.html#authorizesecuritygroupingress) If you are still having an issue, I'd recommend reaching out on [the EC2 forums.](https://forums.aws.amazon.com/forum.jspa?forumID=30)

**Comment by Grace0320** [comment]
I am still seeing this issue. I am making a SecurityGroupIngress rule in the same way, and while the rule is created and there are no errors, the Description remains blank. Are there any working examples?

**Comment by captn3m0** [comment]
[This](https://github.com/razorpay/concierge/blob/4b9388ef91612800ae329c09bc60a1ab81f4eb02/app/Http/Controllers/HomeController.php#L590-L629) seems to be working for us now.
