### ISSUE TITLE
The specified queue does not exist for this wsdl version

### ISSUE THREAD

**Issue by bhalsodkhushal** [aws/aws-sdk-php-laravel#129]
Getting below error..

My queue region is "ap-south-1"
AWS.SimpleQueueService.NonExistentQueue (client): The specified queue does not exist for this wsdl version.

**Comment by kstich** [comment]
This is usually due to an incorrect queue name or client configuration. Please make sure the client you are using is set to the right region, and that the queue name you specified is exactly correct from SQS.

**Comment by devotebest** [comment]
@kstich How to check in detail?

**Comment by mcwqy9** [comment]
I encountered this with code that calls list_queues, and the iterates over the list calling get_queue_attributes for each queue. A deleted queue seemingly can appear in list_queues for a few seconds, leading to a race condition. 

Or maybe my code just hung in execution for unrelated reasons, and the queue was deleted between my call to list_queues and my call to get_queue_attributes for that queue.

The solution in my case was to rescue from that error and move on to the next queue.

**Comment by lcfarrington92** [comment]
I am seeing this error as well.  "The specified queue does not exist for this wsdl version.".  The queue is present and when I call the AWS CLI (get-queue-url) using the same credentials, region and queue name, I do get the queue back.  Using latest version of 1.11.  Any recommendations on how to fix this?

**Comment by zviagins** [comment]
use queue url works for me

**Comment by chokhareganesh** [comment]
I tried with 
`sqs = boto3.client('sqs', region_name="eu-west-1",)
`

**Comment by snobear** [comment]
If you're accessing a queue in another AWS account, you need to specify the queue owner Id. For example, with the aws cli:

```
aws sqs get-queue-url --queue-name example-queue-name.fifo --region us-west-2 --queue-owner-aws-account-id 1234567890
```

**Comment by andreas-ekman-wcar** [comment]
In our team we seem to have issues on unix machines (Ubuntu 18.04/20.04) but Windows machines works fine.

**Comment by mynameismud** [comment]
We're running .NET Core on Ubuntu. Got this error message because the queue URL had the wrong casing.

EX: The queue URL was...
https://sqs.us-west-2.amazonaws.com/000123456789/some-sqs-name-qa.fifo

And we had configured...
https://sqs.us-west-2.amazonaws.com/000123456789/some-sqs-name-QA.fifo

That was all.

**Comment by ankitatalgotra123** [comment]
I am getting the error "2020-09-10T16:15:11:DEBUG:localstack.services.awslambda.lambda_api: Unable to poll SQS messages for queue arn:aws:sqs:us-east-1:000000000000:test_queue: An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the GetQueueUrl operation: The specified queue does not exist for this wsdl version."
Here are the steps i followed:
Created a Lambda Function:
aws lambda create-function --endpoint-url=http://localhost:4574 --function-name samplelambda --runtime java11 --handler lambda.snsEventHandler --zip-file fileb://C:\Workspace\AWSExample\csg-localstack-example\build\libs\lambdademo-1.0.0.jar --role arn:aws:iam::1234567:role/anything --environment Variables="{PROFILE=LOCAL,AWS_REGION=us-east-1}"

Create sqs queue:
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test_queue

Did and event source mapping:
aws --endpoint-url=http://localhost:4566 lambda create-event-source-mapping --event-source-arn arn:aws:sqs:us-east-1:000000000000:test_queue --function-name samplelambda

Sent a message to the queue:
aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/test_queue --message-body “TestMessage!”
OS: windows 10
and i am getting this error. Could you please help?

**Comment by G-bgyl** [comment]
@ankitatalgotra123 Is it because the endpoint portal is not consistant - `4566` VS `4574`?

**Comment by mcshiz** [comment]
If you are trying to delete a message using a ReceiptHandle of a non existent message, you will receive this error too. Very Confusing

**Comment by mariadb-nickvenenga** [comment]
You can also get this if you fail to specify `region` key in mailer config. Despite queues containing region information, an AWS client for a different region may be constructed triggering this error

**Comment by shankFabWork** [comment]
I have written the wrong region

**Comment by Jagan-P** [comment]
> If you are trying to delete a message using a ReceiptHandle of a non existent message, you will receive this error too. Very Confusing

@mcshiz  This was the exact reason in our case. Due to an incorrect env variable of queue url in message deletion, we are getting this error. Really a confusing error message. Thanks for this!

**Comment by SonNXP** [comment]
I fixed the issue "The specified queue does not exist for this wsdl version." by using:
     .withEndpointConfiguration(new EndpointConfiguration(serviceEndpoint, propService.getAwsRegion()))
     (serviceEndpoint = "http://localhost:4566";)
   replace for (when create AwsClient):
     .withRegion(propService.getAwsRegion())

**Comment by lemonScaletech** [comment]
problem was wrong region for me.

**Comment by kbranchuser** [comment]
I'm getting this issue when our region is correct and I have verified no character misconfigurations. Any other ideas?

**Comment by InfiVinay** [comment]
if you are using 
String queueUrl = amazonSQS.getQueueUrl(queueName).getQueueUrl();
            log.info("Queue URL: {}", queueUrl);
            SendMessageRequest sendMessageRequest = new SendMessageRequest(queueUrl, payload);
this in your your SqsService , then check for queueName in your application.properties file , do not pass complete URL in for aws.sqs.queue.name just pass the queueName
