### ISSUE TITLE
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint: "s3.amazonaws.com".

### ISSUE THREAD

**Issue by rahulparekh** [aws/aws-sdk-php-laravel#13]
This is my code:

```
$s3 = App::make('aws')->get('s3');
$s3->putObject(array(
    'Bucket'     => 'actual bucket name here',
    'Key'        => 'random key',
    'Body'   => fopen('file path here','r'),
));
```

If I set an end point like this:

```
$s3 = App::make('aws')->get('s3');
$s3->setEndpoint('s3-eu-west-1.amazonaws.com');
$s3->putObject(array(
   'Bucket'     => 'actual bucket name here',
   'Key'        => 'random key',
   'Body'   => fopen('/home/rahul/public_html/instrumental.mp3','r'),
));
```

I get the following error:
**Argument 2 passed to Guzzle\Service\Client::getCommand() must be an array, string given, called in /home/rahul/public_html/qikview/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php on line 76 and defined**

I've tried replacing body with SourceFile too and it doesn't help. Any solution?

**Comment by kavithasrinu** [comment]
hey, hi when I am trying to access through the s3 with this code but Iam getting this erroe can anyone help me..
input {
    s3 {
    bucket => 'mylogtrail'
    secret_access_key => '*****************************'
    access_key_id => '************************ '
    delete => false
    interval => '60'
    region => 'us-west-2'
    }
}












 plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::S3 bucket=>"mylogtrail", secret_access_key=>"***********************************", access_key_id=>"**********", delete=>false, interval=>60, region=>"us-west-2", codec=><LogStash::Codecs::Plain charset=>"UTF-8">, use_ssl=>true, temporary_directory=>"/tmp/logstash">
  Error: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. {:level=>:error}

**Comment by cjyclaire** [comment]
@kavithasrinu could you check that your bucket region and endpoint matches?

**Comment by vj0555** [comment]
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Endpoint>s3.amazonaws.com</Endpoint><Bucket>jenkinsartefacts</Bucket><RequestId>TJHRGZ2BHD5PNMCH</RequestId><HostId>ZhAQ1H357BskX0Ey138muofh2YyU4SaXM9nSLoC4E43nFkB3ji3C5vTuDFTMDzR3m4+FrccdM/Y=</HostId></Error>

**Comment by NhatDuy11** [comment]
table=spark.sql("""
    CREATE TABLE default.iceberg_table12 (
        id INT,
        data1 STRING
    )
    USING ICEBERG
""")
Py4JJavaError: An error occurred while calling o57.sql.
: software.amazon.awssdk.services.s3.model.S3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: S3, Status Code: 301, Request ID: A6CWB28TSYH7T0C0, Extended Request ID: YgNLdKrEQHNWgWE/0IIbvUXrg0n9yC5+C3YIENe1WWcZDUWNYQvpnwqm4SaQs4ZwmBrcjHzDeIE=)
