### ISSUE TITLE
Store object as 0 byte

### ISSUE THREAD

**Issue by rahul7p** [aws/aws-sdk-php-laravel#131]
I faced issue using laravel.When I upload on bucket then object is uploaded but it's show me 0 byte.

$s3 = \App::make('aws')->createClient('s3');
$s3->PutObject(array(
'Bucket' => 'bucket_name',
'Key' => $file,
'sourceFile' => $destinationPath.$file,
'Content-Type' => $imageFile->getClientMimeType(),
'ACL' => 'public-read-write'
));

https://user-images.githubusercontent.com/38216426/38500758-f805e32a-3c28-11e8-8b06-7151e43f12bb.png

please help...

**Comment by kstich** [comment]
If you're still having this issue, `'sourceFile'` needs to be capitalized to `'SourceFile'`.
