### ISSUE TITLE
Error in file upload 

### ISSUE THREAD

**Issue by raksrivastava** [aws/aws-sdk-php-laravel#134]
My code is below 
 $fileName = uniqid() . '.png';
                            $s31 = \AWS::createClient('s3');
                            $s31->putObject(array(
                                'Bucket' =>BUCKET_NAME.'/abc',
                                'Key' => $fileName,
                                'SourceFile' => 'https://s3-us-west-2.amazonaws.com/xyz/ijk/no_image.png',
                            ));

I am getting below error.
2018-06-21 06:46:01] local.ERROR: Error retrieving credentials from the instance profile metadata server. (Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `404 Not Found` response:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "htt (truncated...)
) {"exception":"[object] (Aws\\Exception\\CredentialsException(code: 0): Error retrieving credentials from the instance profile metadata server. (Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `404 Not Found` response:

**Comment by kstich** [comment]
This issue is due to a misconfiguration in your credentials. Please see [the plugin configuration section](https://github.com/aws/aws-sdk-php-laravel#configuration) and [the SDK credentials configuration section](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html).
