### ISSUE TITLE
Add new release 3.1.1

### ISSUE THREAD

**Issue by ttsuru** [aws/aws-sdk-php-laravel#137]
Please release the version suppot to Laravel Auto Discovery.

**Comment by ttsuru** [comment]
@howardlopez Could you tell me release plan?

**Comment by ttsuru** [comment]
@howardlopez Please release. Only add new tag.

**Comment by howardlopez** [comment]
@ttsuru I apologize for the delay. A new release has been cut: https://github.com/aws/aws-sdk-php-laravel/releases/tag/3.2.0

**Comment by ttsuru** [comment]
@howardlopez Thanks!
