### ISSUE TITLE
Pinpoint - OriginationNumber not working in sendMessages

### ISSUE THREAD

**Issue by pavinthan** [aws/aws-sdk-php-laravel#138]
Hi,

I've tried to sent sms from my PROMOTIONAL numbers which once I got from AWS but I could not receive any messages from my  ORIGINATION_NUMBER.

```
.env
....
ORIGINATION_NUMBER="~removed~"
....
```

```
PinpointMessageSend
....
$this->client->sendMessages([
    'ApplicationId' => $applicationId,
    'MessageRequest' => [
        'Addresses' => [
            $receiver['Address'] => [
                'ChannelType' => 'SMS',
            ]
        ],
        'MessageConfiguration' => [
            'SMSMessage' => [
                'Body' => $message,
                'OriginationNumber' => env('ORIGINATION_NUMBER'),
                'MessageType' => 'PROMOTIONAL',
            ],
        ],
    ],
]);
...
```

Thanks,
Pavinthan.

**Comment by pavinthan** [comment]
Any updates?

**Comment by diehlaws** [comment]
Thanks for reaching out to us @pavinthan, and I do apologize for the delay in our response on this. We'll need some additional information to better understand exactly what you're running into here.

1. Is your `ORIGINATION_NUMBER` one that you have requested from AWS Support in a limit increase? If so, is it a short code or long code?
2. Is the PROMOTIONAL number that you mention the same as your `ORIGINATION_NUMBER`? This is not exactly clear from your description of the issue.
3. When you issue the `sendMessages` request, do you receive any errors from the SDK or from the service?
4. Can you enable [wire logging](https://aws.amazon.com/blogs/developer/wire-logging-in-the-aws-sdk-for-php/) on the SDK and provide the sanitized output here for our review?

Please keep in mind that this particular repository is for the AWS Service Provider for Laravel 5. As such, any issues submitted in this repository should be specific to this service provider and not about behavior within the AWS SDK for PHP itself. Any issues with the SDK itself should be submitted under the [AWS SDK for PHP repository](https://github.com/aws/aws-sdk-php/issues) instead.

**Comment by vccabral** [comment]
I am getting the same behavior from the python library.  Maybe it is in the rest client.
