### ISSUE TITLE
PHPStorm hinting 'Undefined class AwsServiceProvider'

### ISSUE THREAD

**Issue by umbertix** [aws/aws-sdk-php-laravel#141]
While using Laravel 5.7 and PHPStorm the IDE give a warning on 'Undefined class AwsServiceProvider' and would not resolve correctly. It's not a big deal since the Facade work correctly but suggests that something might not be 100% correct.

I've followed the instllation instructions and I'm able to use the facade (haven't really put in use yet, but it's not breaking or giving warnings)

Not sure this is an actual bug but rather a nice to.

Thx for the package.
![undefinedclass](https://user-images.githubusercontent.com/708948/47367129-5a8c5f00-d6df-11e8-9e6d-9f3f854bf5a7.png)

**Comment by howardlopez** [comment]
A package that may be helpful to you is [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper). Let us know how it goes!

**Comment by umbertix** [comment]
Sorry for the slow reply, I'm using it. I was missing to regenerate the file 🤦‍♂️ . The service provide is now recognized but the object auto-completion is still missing. (iamge for example) I'm not sure if this is something with the sdk integration in the library or just down to the ide-helper. 
![untitled](https://user-images.githubusercontent.com/708948/47560747-6e230a00-d919-11e8-96ac-fceb5fc677c2.png)
![untitled2](https://user-images.githubusercontent.com/708948/47560748-6e230a00-d919-11e8-9254-343439ba0fac.png)

Thx anyway for the package.

**Comment by howardlopez** [comment]
It may be worth submitting to that [repository's issues](https://github.com/barryvdh/laravel-ide-helper/issues), as they may have further insight into this.
