### ISSUE TITLE
Is there any way to manage STS token?

### ISSUE THREAD

**Issue by naretini** [aws/aws-sdk-php-laravel#144]
I'm successfully using this service provider to access AWS services through a user's KEY , SECRET pair.

I'm wondering how could I use this (if possible) via STS token : 
https://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-sts.html

**Comment by howardlopez** [comment]
Just FYI, that link is for V2 of the SDK - you can find the [V3 STS guide here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_temporary.html).

Using the service provider, you can access the STS client in a similar way as described in the [README](https://github.com/aws/aws-sdk-php-laravel/blob/master/README.md):

```
$client = \App::make('aws')->createClient('sts');
```

From there you can execute whatever operations you need for your workflow. [This article describes some common scenarios for STS temporary credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html).

Let us know if you have any additional questions.
