### ISSUE TITLE
Found 1 error while validating the input provided for the PutObject operation in S3 PHP SDK to upload docs.

### ISSUE THREAD

**Issue by BhanuRajpoot** [aws/aws-sdk-php-laravel#146]
I have to use S3 PHP SDK to upload docs in AWS S3 bucket, but i am getting an error:

Found 1 error while validating the input provided for the PutObject operation:
[Body] must be an fopen resource, a GuzzleHttp\Stream\StreamInterface object, or something that can be cast to a string. Found bool(false)

$result = $s3Object->putObject([
'Bucket' => $bucketName,
'Key' => $objectKey,
'Body' => fopen($files->file, 'r'),
'Tagging' => $tagingData,
'ACL' => 'public-read'
]);

**Comment by matthewnessworthy** [comment]
@BhanuRajpoot `fopen` returns false on error... it's likely your file doesn't exist or you don't have permissions to read the file.

**Comment by BhanuRajpoot** [comment]
Thanks @matthewnessworthy , i will check again.

**Comment by chandanck1998** [comment]
Check the keys, the first letter must be capital.
