### ISSUE TITLE
I would like to ask you to define the 'namespace' and modify 'phpdoc' so that the editor can complement.

### ISSUE THREAD

**Issue by GILD-MasayaGoto** [aws/aws-sdk-php-laravel#147]
I would like to ask you to define the 'namespace' and modify 'phpdoc' so that the editor can complement.

I can not modify under vendor.

Even if you get an instance from `\ AWS :: createClient ('s3')` and enter it halfway through the editor, you can not complement such as `getObject`.

I'd like to make 'aws-sdk-php-laravel' convenient for developers.

**Comment by howardlopez** [comment]
The [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) package will add some IDE support, allowing you to access `AwsClientInterface` methods for any client made with `createClient`. However, the way the facades are set up, it will still not get you methods specific to a particular client (like S3).

One thing you can do is just use the SDK classes directly, which are found in `vendor/aws/aws-sdk-php/src`:

```
use Aws\S3\S3Client;

...

$s3 = new S3Client($params);
$s3->getObject($params2);
```

If you import the classes this way, your IDE should be able to pick up and auto-complete any client-specific operations.
