### ISSUE TITLE
How can I instruct the service provider to use also the STS token?

### ISSUE THREAD

**Issue by naretini** [aws/aws-sdk-php-laravel#150]
I have a running Laravel 5.5.* application that access AWS services through this package using a specific IAM user's credential, built on purpose.

Now I'd like to improve security and switch to access AWS services with  STS token.
I have my .aws/credentials file correctly set up with a profile with the three var:
AWS_ACCESS_KEY_ID=xxxx
AWS_SECRET_ACCESS_KEY=xxxx
AWS_SESSION_TOKEN=xxxx

Those above are successfully working (have permission) w/ AWS account through aws cli commands.

I thought this could work out of the box so I just copied into my .env file for my Laravel application these three  vars (AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_SESSION_TOKEN) key values , substituting the IAM user ones (AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY) and adding AWS_SESSION_TOKEN.
I'm aware that the token needs to be regenerated and updated for this to work (but it's not the issue, the token I've tested is newly created and working, and I'll take care to update it afterwhile...)
But I'm getting forbidden 403 errors then...
So I believe I need to set somewhere into the Service provider the Token along with Key/secret. Don't I?
Or instruct it to use also the token to issue a AWS client...

Any Idea about how to tweak this?

**Comment by howardlopez** [comment]
Have you published the package configuration, as described [here](https://github.com/aws/aws-sdk-php-laravel#configuration)? This will add an `aws.php` file into your `config` directory, and you can set the credentials to pull from your `.env` file there. For using STS temporary credentials generally with our SDK, you can refer to our [guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_temporary.html).

Let us know if you're still having issues.
