### ISSUE TITLE
Example for Authenticating using AWS Cognito

### ISSUE THREAD

**Issue by eric0324** [aws/aws-sdk-php-laravel#153]
I want to use AWS `Cognito` in `php-laravel`

I already have a Cognito identity pool created

How to use it on `aws-sdk-php-laravel`??

Please help me understand it...

Thanks.

**Comment by alielephant** [comment]
@eric0324 have you managed to do it?

**Comment by eric0324** [comment]
@alielephant No, because I have been dealing with other things recently.

Will be used next month :-)

**Comment by eric0324** [comment]
@diehlaws 

Hi, Is support AWS Cognito?

thank you.
