### ISSUE TITLE
AWS IAM implementation without credentials.

### ISSUE THREAD

**Issue by virkse** [aws/aws-sdk-php-laravel#157]
Im trying to connect with aws without credentials, i mean implementing IAM role to aws and getting this error

 Aws \ Exception \ CredentialsException
Error retrieving credentials from the instance profile metadata server. (cURL error 7: Failed to connect to 169.254.169.254 port 80: Network unreachable (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))

**Comment by diehlaws** [comment]
Hi @virkse, thanks for reaching out to us. You can create anonymous clients in the AWS SDK for PHP by setting `'credentials' => false` in your [client configuration](https://github.com/aws/aws-sdk-php-laravel#configuration). This will prevent the AWS SDK for PHP from looking for AWS credentials in the [default credential provider chain](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html#default-credential-chain).
