### ISSUE TITLE
Request Certificate

### ISSUE THREAD

**Issue by vjoxyodo** [aws/aws-sdk-php-laravel#158]
Hello,

I'm able to create certificates in Certificate Manager using requestCertificate method with ACM Client, but I'm setting the parameter ValidationMethod = "DNS" and the certificate is created but the validation is with email by default. There is something missing in the code? Or this is a generica SDK problem?

**Comment by srchase** [comment]
@vjoxyodo,

Could you provide an example of your ```requestCertificate``` request (with anything sensitive removed)?

**Comment by vjoxyodo** [comment]
@srchase 

Sure. By the way, I update composer to pull last version of the SDK 3.3.2. And the domain I'm using is still not in Route53, the idea is to create first the certificate and then add the DNS validation CNames when creating the domain in Route53

My sample code:
`
$client = AWS::createClient('acm', $credentials);
$request = $client->requestCertificate(
	array(
	    "ValidationMethod" => "DNS",
	    "DomainName" => "example.com"
	)
);

`
	  	    	
Thanks in advanced

**Comment by vjoxyodo** [comment]
@srchase anynews regarding this thread?

**Comment by vjoxyodo** [comment]
Hi,

Managed to solve it. I've checked the problem is in the aws-sdk-php version in the aws-sdk-php-laravel composer. It is setted to version "aws/aws-sdk-php": "~3.0" and It should be "3.92". What did was in my composer install aws-sdk-php latest version. And it started working like a charm for DNS ValidationMethod, hope this input helps in a future update.

**Comment by srchase** [comment]
Thanks for following up!

I'll go ahead and close out this issue.
