### ISSUE TITLE
Trying to describeImages - Allowed memory size exhausted

### ISSUE THREAD

**Issue by edgreenberg** [aws/aws-sdk-php-laravel#166]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
unknown

### Version of AWS Service Provider for Laravel?
3.3.2

### Version of Laravel (`php artisan --version`)?
5.8.28

### Version of PHP (`php -v`)?
7.2.17 

### What issue did you see?
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 219388312 bytes) in /home/edg/PhpstormProjects/AWSData/vendor/guzzlehttp/psr7/src/Stream.php on line 80

### Steps to reproduce
If you have a runnable example, please include it as a snippet or link to a repository/gist for larger code examples.

```
        $ec2 = \App::make('aws')->createClient('ec2');
        $object = $ec2->describeImages([
            'filter' => 'Name=owner-id,Values=xxxxx'
        ]);
```

### Additional context

trying to do this...
```
aws ec2 describe-images --filter 'Name=owner-id,Values=xxxxx' --region us-east-1
```
Any additional information relevant to the issue, for example PHP/environment config settings if the issue is related to memory or performance.

Is it possible that I'm just not doing this correctly? 

Thanks

**Comment by howardlopez** [comment]
Is it possible to increase your PHP memory limit from the current 128M that you have currently (to say 1G)? `DescribeImages` often returns a very large result set that may push up against the memory limit.

**Comment by diehlaws** [comment]
@edgreenberg something to keep in mind with EC2's `describeImages` call is that using the `filter` parameter results in the SDK retrieving all AMIs available in the region in which the call is being made, then the filter is applied client-side to return only the images that match the filter. If you're just trying to retrieve a list of images that belong to a given AWS account you can use the `Owners` parameter which will filter the list on the service end before it is returned to the SDK, resulting in a lower memory consumption from the call.

```
$object = $ec2->describeImages([
    'Owners' => [
        '012345678901',
        '123456789012'
    ]
]);
```
