### ISSUE TITLE
Laravel 6.0 Compatibility 

### ISSUE THREAD

**Issue by djfrailey** [aws/aws-sdk-php-laravel#168]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.107.1

### Version of AWS Service Provider for Laravel?
3.3.2

### Version of Laravel (`php artisan --version`)?
6.0

### Version of PHP (`php -v`)?
7.3.7

### What issue did you see?
The dependency of `illuminate/support` needs to be updated from `~5.1` to `~5.1||~6.0`

**Comment by djfrailey** [comment]
I have opened a pull request to address this issue: https://github.com/aws/aws-sdk-php-laravel/pull/169

**Comment by Athuli7** [comment]
This is needed 1 of 2 packages out of 24 that is holding up the upgrade. The Laravel upgrade guide mentions nothing that should conflict. Moreover, v6 was just a versioning system update.

**Comment by Athuli7** [comment]
This is the need of the hour.

**Comment by howardlopez** [comment]
Thanks everyone. The changes have been merged and released in [3.4.0](https://github.com/aws/aws-sdk-php-laravel/releases/tag/3.4.0)
