### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by neoacevedo** [aws/aws-sdk-php-laravel#172]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.4.0

### Version of AWS Service Provider for Laravel?
AWS S3

### Version of Laravel (`php artisan --version`)?
5.5.48

### Version of PHP (`php -v`)?
7.3.10

### What issue did you see?
Error executing "PutObject" on "https://s3.amazonaws.com/bucket/filename"; AWS HTTP error: Client error: `PUT https://s3.amazonaws.com/bucket/filename` resulted in a `403 Forbidden` response:
SignatureDoesNotMatch (client): The request signature we calculated does not match the signature you provided. Check your key and signing method.

### Steps to reproduce
```php
$s3 = App::make('aws')->createClient('s3');
        $s3->putObject(array(
            'Bucket' => config()->get('app.s3_bucket'),
            'Key' => "filename",
            'Body' => 'Content',
        ));
```

### Additional context
N/A

**Comment by gmansilla** [comment]
I've seen this issue happening on other aws clients (js, ruby, etc.)

Some people fixed it by regenerating the secret key (some clients would behave oddly if the key contained special characters).
Some clients had issues if the signature contained spaces.

I hope this gives you and idea.

**Comment by neoacevedo** [comment]
Yes, I had to create a new access/secret key and worked. But the first access/secret key was created just when I tried the code and the previous key didn't have any special character. The second new one has some special characters.

**Comment by ajredniwja** [comment]
@neoacevedo Is this still an issue? Would like to close it if it has been solved.
