### ISSUE TITLE
I can't connect to Amazon AWS from windows local environment.

### ISSUE THREAD

**Issue by robertmylne** [aws/aws-sdk-php-laravel#175]
From windows computer whenever I try to do a request using the SDK:
`cURL error 7: Failed to connect to 169.254.169.254 port 80: Network unreachable (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)` 

`Can't ping`

Works from ubuntu server. `Can ping`.

Exact same code base. Basically a copy paste. Works if I move code between ubuntu servers, won't work from other windows 10 computers though.

**Comment by robertmylne** [comment]
`The SDK uses the getenv() function to look for the AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN environment variables.`

The `getenv()` function doesn't find the environment variables on a Windows PC, but does on linux. So that's the issue.

**Comment by lloistborn** [comment]
I have the same issue @robertmylne 
any workaround to fix the CLI to be able to curl 169.254.169.254 port 80?
