### ISSUE TITLE
support laravel 7

### ISSUE THREAD

**Issue by Tamrael** [aws/aws-sdk-php-laravel#178]
### Feature description
Support for upcoming laravel 7.*

could you be so kind as to add support for the upcoming laravel 7.* which will be released tomorrow?

Thank you in advance

**Comment by GrahamCampbell** [comment]
Should be quite easy. I don't think there are any changes in L7 that should break this code, if it already works on L6.

**Comment by jdavidbakr** [comment]
https://github.com/aws/aws-sdk-php-laravel/pull/181
