### ISSUE TITLE
Call to undefined function GuzzleHttpormalize_header_keys().

### ISSUE THREAD

**Issue by anuragyadav8949** [aws/aws-sdk-php-laravel#187]
@trevorrowe  @tomschlick  @nickfan  @jeremeamia  @digitalfiz 
This might be not revlevent with the package,
but while Upload/Downloading a object from the Bucket i am facing this issue.
Does anyone have any idea, what it is actually.

```
(1/1) FatalThrowableErrorCall to undefined function GuzzleHttpormalize_header_keys()
--
in EasyHandle.php line 54
at EasyHandle->createResponse()in CurlFactory.php line 545
at CurlFactory->GuzzleHttp\Handler\{closure}(resource, ' ')
at curl_multi_exec(resource, 1)in CurlMultiHandler.php line 108
```

My Code
```
$path = public_path() . "/assets/app_lang/en/GetCrew_English.json";

            $s3 = AWS::createClient('s3');
            echo "<pre>";
            // print_r($s3);

            $result = $s3->getObject([
                'Bucket'     => env('AWS_S3_BUCKET'),
                'Key'        => env('AWS_S3_KEY'),
                'SourceFile' => $path
            ]);
            dd($result);
```

**Comment by GrahamCampbell** [comment]
I you upgrade to the latest version of Guzzle 6, this error will be resolved.

**Comment by anuragyadav8949** [comment]
> I you upgrade to the latest version of Guzzle 6, this error will be resolved.

Thanks a alot for the prompt reply.
My composer.lock has this "guzzlehttp/guzzle": "^5.3.3|^6.2.1",

**Comment by GrahamCampbell** [comment]
What version is actually installed?

**Comment by anuragyadav8949** [comment]
> What version is actually installed?

Thank's That error is resolved,
When  i installed 6.3, but Now whenever i print the values for the file i am not getting anything but a blank response
`            $exists = Storage::disk('s3')->exists('lang/en.json');
`
And my File is on the server which is accesible from a new laravel application but the same is not getting here **showing file not found exception**
`$get = Storage::disk('s3')->get('lang/en.json');`

**Comment by GrahamCampbell** [comment]
You need the very latest 6.5.x release.

**Comment by diehlaws** [comment]
Thanks for reaching out to us @anuragyadav8949. As @GrahamCampbell suggests you should update Guzzle to 6.5. Please do let us know if you continue experiencing this behavior after updating Guzzle.

**Comment by anuragyadav8949** [comment]
> You need the very latest 6.5.x release.

Apologies for not reverting.
Thanks a lot for your help @GrahamCampbell  it solves my S3 issue but showing some guzzelhttp() issue.
Which I am trying to resolve might be some project internal issue.

once again thanks for helping me out @GrahamCampbell  :)

**Comment by anuragyadav8949** [comment]
> You need the very latest 6.5.x release.

This Worked in laravel 5.4 have  change to,
`                "guzzlehttp/guzzle": "^5.3.3|^6.2.1|^7.0",
`
Which resolves my issue
Thanks @GrahamCampbell  for the help

**Comment by GrahamCampbell** [comment]
> "guzzlehttp/guzzle": "^5.3.3|^6.2.1|^7.0",

Don't use Guzzle 7 if you're on Laravel 5.4 `guzzlehttp/guzzle:^6.5.5` should do the job.

**Comment by anuragyadav8949** [comment]
> > "guzzlehttp/guzzle": "^5.3.3|^6.2.1|^7.0",
> 
> Don't use Guzzle 7 if you're on Laravel 5.4. Use:
> 
> ```json
>     "guzzlehttp/guzzle": "^6.5.5",
> ```

I @GrahamCampbell I I got the file not found issue even though my file is on S3,
Can u tell me. should I change into composer.lock file. with the above version.
