### ISSUE TITLE
Does "aws-sdk-php-laravel" support retry mechanism to avoid throttling?  

### ISSUE THREAD

**Issue by SonalikaMishra** [aws/aws-sdk-php-laravel#190]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
Example: v3.133.6
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

Version of AWS SDK for PHP :
v3.139.1
**Version of AWS Service Provider for Laravel?**
v3.5.0

**Version of Laravel (`php artisan --version`)?**
Laravel Framework Lumen (6.3.3) (Laravel Components ^6.0)

**Version of PHP (`php -v`)?**
PHP 7.3.21
**Describe the question**
We are currently using a lumen framework provided service layer on top of aws-sdk-php called aws-sdk-php-laravel. We are facing some throttling issue with ELB (describeTags).(AWS)
Throttling (client): Rate exceeded - <ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/
is there any way to configure service client for elb to use "retry" in our case?
 "aws-sdk-php-laravel" is it supports retry mechanism?

**Comment by GrahamCampbell** [comment]
Yes, the AWS SDK already backs off and retries requests that are rate limitied.

**Comment by SonalikaMishra** [comment]
Could you please share documentation for this and how to configure it's service client for EC2 services?
