### ISSUE TITLE
Error retrieving credentials from the instance profile metadata service.

### ISSUE THREAD

**Issue by arthimann** [aws/aws-sdk-php-laravel#197]
Confirm by changing [ ] to [x] below:
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)

**Version of AWS SDK for PHP?**
Example: v3.133.6
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of AWS Service Provider for Laravel?**
3.6

**Version of Laravel (`php artisan --version`)?**
8.15.0

**Version of PHP (`php -v`)?**
7.4.1

**Describe the question**
After running the command: `php artisan config:cache` for some reason I always got this error:
```
Error retrieving credentials from the instance profile metadata service
```
If I'll use the following command: `php artisan config:clear` it's work fine. Now, to work with the socket server I need those cached config files. Basically, as I understand if I will cache the configuration file, the SDK cannot see the connection credentials. Basically, the issue is not only with only one AWS service it's with all of them (SNS, SES, S3, SQS, etc).

**Comment by danwall** [comment]
The reason that this happens is that the provided [`aws_default.php`](https://github.com/aws/aws-sdk-php-laravel/blob/6d0c895989a5fd6e8abe00b371c6c7e217848d53/config/aws_default.php) config file does not contain the credentials section which loads from the environment with `env()`.

If you publish the config file [`aws_publish.php`](https://github.com/aws/aws-sdk-php-laravel/blob/6d0c895989a5fd6e8abe00b371c6c7e217848d53/config/aws_publish.php) using `php artisan vendor:publish  --provider="Aws\Laravel\AwsServiceProvider"` then as this file does contain the credentials section so using a cached config will work as expected.

This is described in the [configuration section](https://github.com/aws/aws-sdk-php-laravel#configuration) of the readme, however it is not clear that the default file is actually different from the default published file.

**Comment by yenfryherrerafeliz** [comment]
Hi @arthimann, is this a persistent issue for you?, if so, have you tried the recommendation from @danwall in this comment [here](https://github.com/aws/aws-sdk-php-laravel/issues/197#issuecomment-771227370)?, which I confirm that is correct.

Thanks!
