### ISSUE TITLE
Class IVSClient

### ISSUE THREAD

**Issue by irfanDC** [aws/aws-sdk-php-laravel#200]
https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-ivs-2020-07-14.html#createchannel

How can we use the IVS, in the available aws-sdk-php-laravel 3.4 it does not exists. Please help

**Comment by yenfryherrerafeliz** [comment]
Hi @irfanDC, thanks for opening this issue and sorry for the delayed response. I can confirm that on version 3.7 the IVS client is present. So, could you please update to the latest SDK version and then try on your end?.

Thanks!
