### ISSUE TITLE
Error Unresolvable dependency resolving [Parameter #0 [ <required> array $args ]] in class Aws\AwsClient

### ISSUE THREAD

**Issue by leonildojunior** [aws/aws-sdk-php-laravel#201]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php-laravel/issues) and didn't find any solution
  
**Describe the bug**
After performing the settings indicated in the documentation, I tried to use it in a service, according to the code below, and I got the error: `Unresolvable dependency resolving [Parameter #0 [ <required> array $args ]] in class Aws\AwsClient`

my code

```php
namespace App\Services\Xpi;

use Aws\Exception\AwsException;
use Aws\SecretsManager\SecretsManagerClient;
...
  $clientAWS = new awsSecretManage([
             'profile' => 'default',
             'version' => 'latest',
             'region' => env('AWS_REGION'),
         ]);

         $token_development = $clientAWS->getSecretValue([
             'SecretId' => 'bff-dsv',
         ]);
```
And on the controller

```php
use App\Services\Xpi\Client;

$clientXP = $clientXP->getClient('xxxxxx');
```

**Version of AWS SDK for PHP?**
**** 

**Version of AWS Service Provider for Laravel?**

**Version of Laravel (`php artisan --version`)?**
 3.185.2

**Version of PHP (`php -v`)?**
7.3.22

**Screenshots**

<img width="620" alt="Captura de tela 2021-06-27 184826" src="https://user-images.githubusercontent.com/78820752/123560574-c934eb00-d7ab-11eb-8714-56b41be5e362.png">

**Comment by matiaslauriti** [comment]
You are showing 2 different issues here, one is `Unresolvable dependency` and other one is `Target class does not exist.`.

**Comment by yenfryherrerafeliz** [comment]
Hi @leonildojunior, thanks for opening this issue. I am not able to reproduce the reported behavior, and some details are missing to understand better your implementation. For example, I do not know what the following code means:
```php
use App\Services\Xpi\Client;

$clientXP = $clientXP->getClient('xxxxxx');
```
For what I see, you are trying to call a method from the same variable that you just declared. 

So, could you please let me know if this is a persistent issue for you, if so, could you please provide more clear and specific details about how to reproduce the issue?

For my reproduction I followed the next steps:
- Created a Laravel project:
    - ```console composer create-project laravel/laravel MY-PROJECT-NAME ```
- Then, I followed the steps from the [documentation](https://github.com/aws/aws-sdk-php-laravel/blob/master/README.md) to install the required dependencies and set up the necessary configuration.
- Then, I created a test controller with a method where I wrote the following code:
     ```php
    $clientAWS = new SecretsManagerClient([
            'profile' => 'default',
            'version' => 'latest',
            'region' => 'us-east-2',
        ]);

        $tokenDevelopment = $clientAWS->getSecretValue([
            'SecretId' => 'SECRET-ID',
        ]);

        return response()->json($tokenDevelopment->get('data'));
- Configured the routing, and when I access to it I got the following response:
    ```console
    {
    "statusCode": 200,
    "effectiveUri": "SERVICE",
    "headers": {
        "x-amz-id-2": "ID",
        "x-amz-request-id": "REQ-ID",
        "date": "Mon, 03 Oct 2022 13:25:55 GMT",
        "content-type": "application/xml",
        "transfer-encoding": "chunked",
        "server": "AMAZON-SERVICE"
    },
    "transferStats": {
        "http": [
            []
        ]
    }
}
    ```
Thanks!

**Comment by FiodorCroitor** [comment]
Lol kek cheburek
