### ISSUE TITLE
AWS.SimpleQueueService.NonExistentQueue (client): The specified queue does not exist for this wsdl version.

### ISSUE THREAD

**Issue by razzaa** [aws/aws-sdk-php-laravel#204]
Aws\Sqs\Exception\SqsException
Error executing "ReceiveMessage" on "https://sqs.us-east-2.amazonaws.com/***********/notification"; AWS HTTP error: Client error: `POST https://sqs.us-east-2.amazonaws.com/*************/notification` resulted in a `400 Bad Request` response:
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>A (truncated...)

**Comment by yenfryherrerafeliz** [comment]
Hi @razzaa, thanks for reaching out. Is this a persistent issue for you?, if so, could you please provide more details about your implementation?. As the minimum we would need the following:
- SDK version being used
- Self contained reproducible code

I also found the following [issue](https://github.com/aws/aws-sdk-php-laravel/issues/129), which may contains helpful information so you can fix the issue on your end.

Thanks!
