### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by abrampl** [aws/aws-sdk-php-laravel#206]
Helo,
When we can expected laravel 9 support ?

**Comment by SamRemis** [comment]
@abrampl should have just been merged with https://github.com/aws/aws-sdk-php-laravel/pull/209 :)

**Comment by MarkVaughn** [comment]
Sweet! Thank you @SamRemis, now only thing left to do is tag a new release

**Comment by SamRemis** [comment]
@MarkVaughn thanks for reminding me :) should be good now
