### ISSUE TITLE
Laravel 8.6 Unable to parse error information from response - Error parsing XML: String could not be parsed as XML

### ISSUE THREAD

**Issue by cheran2017** [aws/aws-sdk-php-laravel#208]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php-laravel/issues) and didn't find any solution
  
**Describe the bug**

**Version of AWS SDK for PHP?**
Example: v3.209.30
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of AWS Service Provider for Laravel?**
v3.6

**Version of Laravel (`php artisan --version`)?**
8.6

**Version of PHP (`php -v`)?**
8.0.1

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
Normally it's showing
**Expected behavior**
success response and job dispatch in queue
**Screenshots**
<img width="1185" alt="Screenshot 2022-02-25 at 11 22 08 AM" src="https://user-images.githubusercontent.com/25399522/155661946-50f82da4-c7f8-4719-9a75-32a3a8667fd9.png">

**Additional context**
Any additional information relevant to the issue. Examples include any framework you may be using (e.g. Laravel, Wordpress) in conjunction with the AWS SDK for PHP, or PHP/environment config settings if the issue is related to memory or performance.

**Comment by SamRemis** [comment]
@cheran2017, looks like SQS may be sending us invalid XML.  Can you give me steps to reproduce this?
