### ISSUE TITLE
Should be laravel 9.0 - right?

### ISSUE THREAD

**Issue by DeepDiver1975** [aws/aws-sdk-php-laravel#211]
https://github.com/aws/aws-sdk-php-laravel/blob/cfae1e4e770704cf546051c0ba3d480f0031c51f/CHANGELOG.md?plain=1#L5

**Comment by SamRemis** [comment]
Yes, thank you for pointing that out, I need to go fix that :)

**Comment by SamRemis** [comment]
Looks like something went wrong when the changelog was auto-populated.  Fixed the entry, and it should be good now.
