### ISSUE TITLE
Support Laravel 10

### ISSUE THREAD

**Issue by lptn** [aws/aws-sdk-php-laravel#222]
### Describe the feature

Laravel 10 has released today, I would like to use it with this package

### Use Case

Laravel 10 + aws/aws-sdk-php :)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

latest

### Environment details (OS name and version, etc.)

-

**Comment by nickdavies791** [comment]
Would also appreciate this package having support for Laravel 10 - it's our only sticking point for upgrading at the moment.

**Comment by FB-LilianaIturribarria** [comment]
Same here... 👯 i need this package to support laravel 10 in order to upgrade
