### ISSUE TITLE
aws-sdk-php (3.281.13) generates error

### ISSUE THREAD

**Issue by closca** [aws/aws-sdk-php-laravel#235]
### Describe the bug

composer.json has "aws/aws-sdk-php": "~3.0" and on composer install/update will take version 3.281.13
unfortunatly, aws-sdk-php-laravel is not ready for version 3.281.13 as it throws the following error
`TypeError Aws\EndpointV2\EndpointProviderV2::__construct(): Argument #1 ($ruleset) must be of type array, null given, called in /vendor/aws/aws-sdk-php/src/ClientResolver.php on line 1049`

### Expected Behavior

To send correct arguments

### Current Behavior

Throws error

### Reproduction Steps

Install lates version of aws-sdk-php-laravel

### Possible Solution

As emergency, we've locked the version into project root composer.json to  "aws/aws-sdk-php": "3.281.12"

### SDK version used

3.8.1

### Environment details (OS name and version, etc.)

Ubuntu 22.04

**Comment by SamRemis** [comment]
Hi there, @closca, could you please tell me what service you're trying to initialize?

**Comment by SamRemis** [comment]
Just to update, I attempted to reproduce this by initializing one copy of each service client in a laravel application; no issue occurred.  This was done on the version that you reported (3.281.13).

Given that no one else has reported this issue, it's possible that you experienced a rare glitch that has impacted a few of our customers where composer installed two versions of the SDK and it led to a mismatch in versions.  I have a few follow-up questions:

1. Did you only try the composer install/update once?  Could you try upgrading again and let us know if the issue persists? 
2. If it is still broken, could you share with us the chunk of code that is causing this issue and a bit more about your environment?  Specifically the laravel version and the PHP version
3. Do you know what version you were upgrading from?  Is this an update that you do frequently, or were you upgrading from a version which was much older?

**Comment by SamRemis** [comment]
In case anyone else runs into this, someone opened a [discussion](https://github.com/aws/aws-sdk-php/discussions/2783) in the upstream repository for this who was running into the same issue.  The [fix](https://github.com/aws/aws-sdk-php/pull/2784) for this has already been merged and will be included in tomorrow's release.  

This issue was specific to one single version of Cloudfront client, and the last version impacted by this bug will be 3.282.0.
