### ISSUE TITLE
Laravel 5 Support

### ISSUE THREAD

**Issue by nolros** [aws/aws-sdk-php-laravel#45]
Any ideas when you will have a version that supports Laravel 5?

**Comment by extra90** [comment]
+1

**Comment by nolros** [comment]
@stephenoldham  and @GrahamCampbell thanks guys. Starting to get my head around the new fly integrated into L5 - thanks a million.

**Comment by mkwsra** [comment]
+1

**Comment by jeremeamia** [comment]
This should be happening soon via https://github.com/aws/aws-sdk-php-laravel/pull/52

**Comment by jeremeamia** [comment]
Give the [AWS Provider for L5 (Beta)](https://github.com/aws/aws-sdk-php-laravel/releases/tag/2.0.0-beta.1) a try.

**Comment by mkwsra** [comment]
Thanks a lot I've been waiting for it

**Comment by mkwsra** [comment]
@jeremeamia Mr.Lindblom, you might want to change the very first line in README.md, Laravel 5
