### ISSUE TITLE
Multiple Region Queries?

### ISSUE THREAD

**Issue by tapsboy** [aws/aws-sdk-php-laravel#47]
The config file generated by the SDK currently supports only one region. But for doing multi-region queries, this approach doesn't work. As a workaround, I can leave the region empty in config, but dynamically set it using Config::set. 

<?php

    getEC2Instances('us-east-1');
    getEC2Instances('us-west-2');

    function getEC2Instances($region)
    {
        Config::set('aws::config.region', $region);
        $ec2 = App::make('aws')->get('ec2');

        $instances = $ec2->describeInstances()->get('Reservations');
    }

?>

However, the provider is only registered once. Thus calling App::make 2nd time re-uses the config provided in the first call. With the standard AWS PHP SDK, we can call the factory multiple times, but doing so here would beat the purpose of IoC. 

Is anyone else running into such issues? Thoughts?

**Comment by jeremeamia** [comment]
I'm sorry that I did not reply to this sooner. A good way to handle this situation is to pass in options to overwrite the config when you call get.

```php
$ec2East = App::make('aws')->get('ec2', ['region' => 'us-east-1']);
$ec2West = App::make('aws')->get('ec2', ['region' => 'us-west-2']);
```
