### ISSUE TITLE
Changing AWS Keys in Run Time

### ISSUE THREAD

**Issue by gayanhewa** [aws/aws-sdk-php-laravel#50]
Hi,

In a multi-tenant setup , its required that we switch the AWS keys of the tenant. 

So far its possible to achieve this via a simple 

       Config::set('aws::key', $tenant->key);
       Config::set('aws::secret', $tenant->secret);

But I have come across an instance where this doesn't work. I can't seem to make sense as to why this happens , the config variables are empty if I debug the Service provider at this point. 

       App::make('aws')->factory($tenant_aws_config)->get('sns');

Doing the above resolve the problem for now, but it doesn't help me understand how this is caused. 

Do advise me if any of you guys have come across such a scenario. 

Regards,

Gayan

**Comment by GrahamCampbell** [comment]
Do this: `App::forgetInstance('aws');`. After setting your new config. That way next time we create the shared aws instance, we re-read the config.

**Comment by gayanhewa** [comment]
Awesome.
