### ISSUE TITLE
The requested package couldn't be found

### ISSUE THREAD

**Issue by mkwsra** [aws/aws-sdk-php-laravel#57]
After I added the package name info Composer.jason, and running update I'm getting the follow error:
 ![Image of the error] (http://ht5-bucket.s3.amazonaws.com/Screen%20Shot%202015-02-19%20at%2012.23.38.png)

any thoughts ?

**Comment by PSutton3756** [comment]
If you are using Laravel 4.2, try specifying version 1.1.2 in your composer.json like so: "aws/aws-sdk-php-laravel": "1.1.2"   . I had the same problem today when I had the version set to dev-master, but switching to 1.1.2 fixed it for me, so hopefully it works for you as well.

**Comment by jeremeamia** [comment]
The 2.0 is still beta, so you will either need to set your `composer.json`'s `minimum-compatibility` setting (probably not the best idea), or you can declare your dependency like this:

    "aws/aws-sdk-php-laravel": "~2.0@beta"

I'm going to update the README to reflect this via https://github.com/aws/aws-sdk-php-laravel/pull/56.
