### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by aniesshsethh** [aws/aws-sdk-php-laravel#58]
I get this error 

Class 'App\Http\Controllers\App' not found when trying to follow the example to the letter in Laravel 5. 

any idea ?

**Comment by jeremeamia** [comment]
I'm not sure why you would get that error. That class isn't a part of this service provider or the AWS SDK.

**Comment by aniesshsethh** [comment]
I am not sure either, but if you do a clean install , you can see it's popping up. I have started using the AWS SDK without the wrapper for now, so no hurry.

**Comment by jeremeamia** [comment]
@GrahamCampbell @tomschlick Any thoughts on why this would happen?

**Comment by tomschlick** [comment]
If in a namespaced controller you need to import App

```php
use \App
```

**Comment by jeremeamia** [comment]
Ah, that makes sense. I forgot L4 didn't really tell people to namespace their controllers. L5 apparently does. I'll update the README with something to make that more clear.

**Comment by martinbean** [comment]
@jeremeamia It does. So if you need to make use of any façades then they need to be imported:

```php
<?php namespace App\Http\Controllers;

use App;
```

Or referenced using the backslash character:

```php
public function foo()
{
    $client = \App::make('aws')->get('s3');
}
```

**Comment by jeremeamia** [comment]
Thanks for clarifying this. Closing.
