### ISSUE TITLE
There are no commands defined in the "vendor" namespace

### ISSUE THREAD

**Issue by jacks8x** [aws/aws-sdk-php-laravel#59]
When I run the command: "php artisan vendor:publish", it get the error message "There are no commands defined in the "vendor" namespace". Can you help me out of this error. Thanks!!

**Comment by jeremeamia** [comment]
I've never com across this before, and I don't think it has anything to do with this package. You may want ask about this on the [Laravel forums](http://laravel.io/forum). If you determine that there is an issue with this package, please reopen the issue with more details.

**Comment by jhoganrg** [comment]
I too am receiving the same error

**Comment by GrahamCampbell** [comment]
You're using the wrong version of laravel then.

**Comment by GrahamCampbell** [comment]
Laravel 5.1 is the only currently supported version of Laravel.

**Comment by GrahamCampbell** [comment]
All other versions are nolonger maintained.

**Comment by boarmanc** [comment]
Getting same error in Laravel 5.1, using Homestead.

**Comment by glsarmenta** [comment]
same error
