### ISSUE TITLE
What can you achieve with this project that you cannot with aws-sdk-php

### ISSUE THREAD

**Issue by BardiaAfshin** [aws/aws-sdk-php-laravel#60]
Why would I want to use this library? What benefit does it provide over aws-sdk-php? Also, how does it compare to python Boto library? Do they overlap in the domain responsibility?

**Comment by jeremeamia** [comment]
> Why would I want to use this library? What benefit does it provide over aws-sdk-php?

This library is merely a small bridge between the [AWS SDK for PHP (aws-sdk-php)](https://github.com/aws/aws-sdk-php) and Laravel. It contains a Laravel ServiceProvider object that instantiates the SDK and hooks it up to Laravel's service container. All of the AWS-specific logic is in the SDK, not this library.

Essentially, this package exists to make it easier for Laravel developers to use the AWS SDK for PHP.

> Also, how does it compare to python Boto library? Do they overlap in the domain responsibility?

Comparing this specific package to Boto doesn't make sense, but the [AWS SDK for PHP](https://github.com/aws/aws-sdk-php) and Boto library do the same thing, just with different programming languages. Both are maintained by my team at AWS.
