### ISSUE TITLE
Showcases of laravel and aws-sdk-php-laravel?

### ISSUE THREAD

**Issue by BardiaAfshin** [aws/aws-sdk-php-laravel#64]
Are there any showcases of how laravel and the aws-sdk-php-laravel are being used together?

**Comment by jeremeamia** [comment]
I did a little bit in [this demo app](https://github.com/jeremeamia/FunnyFacesL4ExampleApp). I tried asking around for some examples on Twitter, but didn't hear back from anyone. Have you asked on the Laravel forums? I would be interested in getting a list of examples as well. If you find any, let me know.

**Comment by jeremeamia** [comment]
Closing due to lack of participation. :disappointed:
