### ISSUE TITLE
Impossible to use AWS APIs with different keys

### ISSUE THREAD

**Issue by Maykonn** [aws/aws-sdk-php-laravel#65]
My S3 configuration has a key and a secret, but other services like SES has other key and secret. How to implement this?

**Comment by jeremeamia** [comment]
You can do this a couple different ways.

First, by using an SDK config file via the service provider's `config_file` options. Look [here](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/credentials.html#using-a-configuration-file-with-the-service-builder) and [here](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/configuration.html#using-a-custom-configuration-file) for help with that.

Second, you can also override configuration when you get a client. For example:

```php

$s3 = App::make('aws')->get('s3', [
    'key'    => env('SES_KEY'),
    'secret' => env('SES_SECRET'),
]);
```

**Comment by Maykonn** [comment]
I will try with config_file. The second way is what I do for now. But a aws config file is better way, I think. Thanks!

**Comment by jeremeamia** [comment]
No problem. :smile:
