### ISSUE TITLE
Compatibility with Lumen

### ISSUE THREAD

**Issue by jszobody** [aws/aws-sdk-php-laravel#67]
The `AwsServiceProvider` currently doesn't work in a Lumen project, because the `config_path` helper function isn't available.

Would it be reasonable to change line 9 (`$this->publishes...`) to first check to see if `config_helper` has been defined?

From what I can tell `$this->publishes...` doesn't need to be run in a Lumen app anyway, and I can still configure Aws using my .env file.

I'd be happy to submit a PR, just wanted to see if this was the right approach.

**Comment by jeremeamia** [comment]
I'm not sure what the correct approach is, and I don't have time to look into it at the moment. If you want to submit a PR, then you'll need to provide some proof that it works for both Laravel and Lumen. That proof could include links to documentation, updated tests, and/or having others verify that it works for them in both environments. I wouldn't merge any changes that I'm not 100% confident are correct.

**Comment by GrahamCampbell** [comment]
A simple solution would be to not use helpers that are only defined by illuminate/foundation. Then this would allow usage in any app that uses laravel components. I'd always recommend that. :)

**Comment by jszobody** [comment]
@GrahamCampbell What's a better way to get the config path?

**Comment by GrahamCampbell** [comment]
Resolve `'path.config'` from the ioc container.

**Comment by jeremeamia** [comment]
I'm not sure what the code change is supposed to be. Anyone want to submit a PR?

**Comment by jeremeamia** [comment]
Will #73 fix this?

**Comment by jeremeamia** [comment]
> Would it be reasonable to change line 9 ($this->publishes...) to first check to see if config_helper has been defined?
> 
> From what I can tell $this->publishes... doesn't need to be run in a Lumen app anyway, and I can still configure Aws using my .env file.

Seems like this might be the better solution after all.

**Comment by jszobody** [comment]
Yeah I'd agree. `'path.config'` isn't in ioc in Lumen, so I'm not sure the #73 change would work anyway.

I've been looking for an official way to detect which framework is being used, seems odd that Taylor hasn't made that available. But since I can't find a way to do that, checking for `config_helper` is probably best.

**Comment by GrahamCampbell** [comment]
I'll send a PR. :)

**Comment by GrahamCampbell** [comment]
https://github.com/aws/aws-sdk-php-laravel/pull/74 should fix everything fo you. :)

**Comment by jeremeamia** [comment]
Sweet. Thanks you two. The `2.0` branch and `master` (3.0) have had this change applied.
