### ISSUE TITLE
How do I specify a custom endpoint using a configuration file?

### ISSUE THREAD

**Issue by sebastiansibelle** [aws/aws-sdk-php-laravel#68]
Hi there,

I'm trying to configure the package to use a custom PHP config file so that I can use a custom endpoint. I can't get the application to use the custom config, I just get a 'Unable to open my/path/to/aws/config.php for reading" error.

I want to use one of the SSLv3 disabled endpoints so that I can test out whether the disabling of support will have an effect on our application. Currently we specify a region, our key and a secret to utilise the SDK. I want to use a config file to set an endpoint as per: http://docs.aws.amazon.com/aws-sdk-php/guide/latest/configuration.html#custom-endpoint 

It sounds like I'm maybe specifying the path wrong, but I've tried all the possibilities I could think of and I can't find any documentation on what format it expects, how to use a custom endpoint using this package or if it is even possible at all. 

Can you provide any help?

Thanks,

Sebastian

**Comment by novakben** [comment]
Joining the question!

**Comment by jeremeamia** [comment]
What does your code look like? I might be able to tell if something is wrong if I can see what you are doing.

You can also set custom options when retrieving a client from the container:
```php
$s3ClientWithCustomEndpoint = AWS::get('s3', ['endpoint' => '...']);
```

**Comment by sebastiansibelle** [comment]
Hey @jeremeamia,

Thanks for your help. 

How do I know that the endpoint is being used when retrieving the client from the container? 
When I try to set the endpoint using custom options like you've suggested and I use bogus data like follows I can still upload to s3. Is there some kind of fallback thing happening here? 

    AWS::get('s3', ['endpoint' => 'foobar']);

I've set up my hosts file to use the following set of S3 endpoints for testing but I can't work out to ensure that they are used:

   54.231.32.0 s3.amazonaws.com
   54.231.32.1 <bucket name>.s3.amazonaws.com
   54.231.32.3 <bucket name>.s3-external-1.amazonaws.com

I want to do something like follows and know that it is using the test endpoint with SSLv3 disabled:

 $s3 = AWS::get('s3', ['endpoint' => 's3.amazonaws.com']);

**Comment by jeremeamia** [comment]
Sorry for the delay. You can see the raw request using the [wire logger](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/faq.html#how-can-i-see-what-data-is-sent-over-the-wire).

**Comment by jeremeamia** [comment]
Closing due to age.
