### ISSUE TITLE
FYI: composer update setup warning - Guzzle

### ISSUE THREAD

**Issue by maximerassi** [aws/aws-sdk-php-laravel#69]
During installation of 2.0 this warning shows up. 
```
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. 
The package you have installed, Guzzle 3, is deprecated.)
```

**Comment by jeremeamia** [comment]
Nothing to worry about there. AWS SDK V2 uses Guzzle V3. Guzzle 3 _is_ deprecated, but is still widely used.

However, AWS SDK V3 should be coming out soon, which will support Guzzle V5 and V6. After that, we will release a new version of this service provider that support AWS SDK V3.

**Comment by maximerassi** [comment]
Great thanks
