### ISSUE TITLE
SES Email Format <end>

### ISSUE THREAD

**Issue by newtonianb** [aws/aws-sdk-php-laravel#70]
I just ran a quick test using this SDK to send an email using SES. All  looks good it was properly sent and received however I noticed some weird ``<end>`` string appended to the end of my message in preview mode
 (at least when using Microsoft Outlook)

![email](https://cloud.githubusercontent.com/assets/2313644/7713271/a0b5b7f0-fe44-11e4-8335-bd4ded8b6275.jpg)

```
        $successStatus = AWS::get('ses')->sendEmail(
            [
                'Source'           => self::formatHeader($fromName, $fromEmail),
                'Destination'      => ['ToAddresses' => $destinationEmails],
                'Message'          => [
                    'Subject' => ['Data' => $emailSubject],
                    'Body'    => ['Text' => ['Data' => $emailBody], 'Html' => ['Data' => $emailBody]],
                ],
                'ReplyToAddresses' => [$fromEmail]
            ]
        );

```

It this something the email browser is adding or is my message somehow corrupt or malformed?

**Comment by jeremeamia** [comment]
I've never seen that before, but I doubt it is caused by the SDK. You should ask on the [SES forums](https://forums.aws.amazon.com/forum.jspa?forumID=90). If you find evidence that suggests the SDK is at fault, please open an issue on the [main SDK repo](https://github.com/aws/aws-sdk-php).

**Comment by BrUn3y** [comment]
well may be is late buy you can try this..
`	$ses = AWS::createClient('ses');

    $ses->sendEmail(array(

        'Source' => 'mailN@yourDomian.com',

        'Destination' => array(

            'ToAddresses' => array('yourEmail@yourDomian.com'),

        ),

        'Message' => array(

            'Subject' => array(

                'Data' => 'subject',

            ),

            'Body' => array(

                'Text' => array(

                    'Data' => 'body mail',
                ),
            ),
        ),
    ));`
