### ISSUE TITLE
us-west-2 does not map correctly

### ISSUE THREAD

**Issue by jalipert** [aws/aws-sdk-php-laravel#76]
(Laravel 5.1, aws version 3.0)
My bucket is hosted on us-west-2, but when I specify us-west-2 in the config, the calls to the API fail.  Changing the config to us-east-1 seems to fix the problem (even though my bucket is hosted on us-west-2)

**Comment by jeremeamia** [comment]
What is the error message you are getting?

**Comment by jalipert** [comment]
my mistake.  I was confused because my management console home stated us-west-2.  The bucket was actually hosted on US Standard.

**Comment by jeremeamia** [comment]
Ah, OK. Thanks for the update.
