### ISSUE TITLE
api is a required option 

### ISSUE THREAD

**Issue by joshhornby** [aws/aws-sdk-php-laravel#77]
I am using the default Laravel SQS queue driver, when I try to push a job onto the queue I am getting the following error:

```
InvalidArgumentException in AwsClient.php line 77:
api is a required option
```

My code for pushing onto the class is a simple Laravel 5.1 job

```
class FooBarClass extends Job implements SelfHandling {  }
```

I am using version ~3.0 of this package and  before updating to Laravel 5.1 this was working, I have updated the ```aws.php``` config file for the new version as well.

**Comment by jeremeamia** [comment]
It looks like you've pulled in the 3.0.0-beta.1 version of the SDK which definitely will not work. One way to get around this would be to add an explicit line in your composer.json for the SDK. This should get you the latest: `"aws/aws-sdk-php": "^3.0.5"`.

**Comment by abixalmon** [comment]
Its caused by 2 things in your composer file.

You need to update Guzzle
```"guzzlehttp/guzzle": "5.3.*",```

Remove this 2 lines for composer.json
```
    "minimum-stability": "dev",
    "prefer-stable": true
```
refer to laravel's default composer file -- https://github.com/laravel/laravel

**Comment by GrahamCampbell** [comment]
Or use guzzle 6. Guzzle 6 is the preferred way since laravel 5.2 has dropped guzzle 5 support.
