### ISSUE TITLE
How can I dynamic change object options?

### ISSUE THREAD

**Issue by iyourplus** [aws/aws-sdk-php-laravel#81]
```php
$object = AWS::createClient('s3');
```
I create a object about s3, and the region is `us-east-1`. I want to dynamic change the region to `ap-southeast-1` or others. So, How can I do that? I use `get_class_methods` method to print `$object` all functions, and I find `factory` method, But it does not work.
```php
$object->factory([
    'region' => 'ap-southeast-1',
    'scheme' => 'http',
    'version' => 'latest'
]);
```

**Comment by jeskew** [comment]
[`createClient`](https://github.com/aws/aws-sdk-php/blob/master/src/Sdk.php#L102) takes an optional second argument. You can pass in an array with keys like `region` and `version`, e.g., `Aws::createClient('s3', ['region' => 'ap-southeast-1'])`.

`factory` is a static method to create a new client and will not alter a client that has already been created.
