### ISSUE TITLE
what is this object Key

### ISSUE THREAD

**Issue by ukenpachi** [aws/aws-sdk-php-laravel#82]
Hi, I have follow the instruction but i am getting errors regarding the "YOUR_OBJECT_KEY"

$filename = \rand() .'_'. ImageService::mt_rand_str(15). '_'. time(). '_s';
try {
		        	$s3 = \AWS::createClient('s3');
		        	$s3->putObject(array(
		        		'Bucket' 			=> 'hprofile-uda1',
		        		'key' 			=> $filename,
		        		'SourceFile'		=> $temp_path.'/'.$filename,
		        		'ACL'			=> 'public-read',
		        		'StorageClass'		=> 'REDUCED_REDUNDANCY'
		        	));
		        } catch (\AWS\Exception\S3Exception $e) {
		        	echo "There was an error uploading the file.\n";
		        }

I successfully dont know what the key is might to be and i have tried both my access key, secret key and bucket name.

I keep getting this error 
Found 1 error while validating the input provided for the PutObject operation:
[Key] is missing and is a required parameter

I have read http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html and it says "When you create an object, you specify the key name, which uniquely identifies the object in the bucket." i have done this

**Comment by jeskew** [comment]
Operation parameters are case sensitive. You are supplying `'key'`, and the operation is looking for `'Key'`.

**Comment by amjadsarwar** [comment]
$s3->putObject([
     'Buckets' => 'sacredstonebooks',
     'Key' => "uploads{$imagename}",
     'Body' => fopen("uploads/".$imagename ,'rb'),
     'ACL'=> 'public-read'
    ]);

**Comment by jeskew** [comment]
@amjadsarwar replace `'Buckets'` with `'Bucket'`.

**Comment by amjadsarwar** [comment]
@jeskew change tis namge buckets to Buctet but issue still panding

**Comment by amjadsarwar** [comment]
@jeskew my video is alredy upload on amazon . how to this video streaming on my local site plz help me
