### ISSUE TITLE
Do i need to point to the SDK?

### ISSUE THREAD

**Issue by MACscr** [aws/aws-sdk-php-laravel#86]
I am completely new to Laravel and have only been using it a couple weeks, but I am not 100% sure how I am supposed to fully utilize your package. Am I supposed to manually configure it to point to the amazon sdk or is that handled somehow automatically or is it even needed?

**Comment by jeskew** [comment]
Hi @MACscr,

You need to install the package and add the appropriate providers to your application as described [here](https://github.com/aws/aws-sdk-php-laravel#installation).

**Comment by MACscr** [comment]
Already did all of that. Were additional packages installed that are not listed in the sources of this github repo? I didnt install it with git, I just do not see much in the package.

**Comment by jeremeamia** [comment]
When you install this package with Composer, it installs the [AWS SDK for PHP](https://github.com/aws/aws-sdk-php) as well. This package is just a Laravel-specific wrapper for that package.
