### ISSUE TITLE
I am getting [Aws\Exception\CredentialsException]   in Lumen.

### ISSUE THREAD

**Issue by piyushpatil027** [aws/aws-sdk-php-laravel#87]
Hi,

Hope you are doing great. I am using lumen framework and I want to integrate aws-sdk-php-laravel.
When I configure and run then i am getting below error.

  [Aws\Exception\CredentialsException]                                                                                                                                                           
  Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))  
                                                  
Can i help me What is actual problem ? Where i am doing wrong.

**Comment by jeskew** [comment]
Hi @piyushpatil027,

I responded on https://github.com/aws/aws-sdk-php/issues/829 as well, but this is a better forum for Laravel-specific questions.

How are you currently providing credentials to the client you're trying to use? Does it look like one of the methods described [here](https://github.com/aws/aws-sdk-php-laravel#configuration)?

**Comment by piyushpatil027** [comment]
Hi Jonathan,

Yes . I have looked that but there is getting error to me that why i used
different method.
Actually I am using Lumen Framework . I spent lot of time but i didnt get
proper solution.

On Fri, Nov 20, 2015 at 12:20 AM, Jonathan Eskew <notifications@github.com>
wrote:

> Hi @piyushpatil027 <https://github.com/piyushpatil027>,
>
> I responded on aws/aws-sdk-php#829
> <https://github.com/aws/aws-sdk-php/issues/829> as well, but this is a
> better forum for Laravel-specific questions.
>
> How are you currently providing credentials to the client you're trying to
> use? Does it look like one of the methods described here
> <https://github.com/aws/aws-sdk-php-laravel#configuration>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-php-laravel/issues/87#issuecomment-158153635>
> .
>



-- 
Thanks & Regards
Piyush Patil


Software Engineer
Sky Id : piyushpatil27
Email Id : piyushpatil027@gmail.com
Mobile No : 09096871715

**Comment by jeskew** [comment]
[Your comment on the SDK issue](https://github.com/aws/aws-sdk-php/issues/829#issuecomment-158153656) indicates that this issue is solved? Is that correct, or are you still getting an error?

**Comment by piyushpatil027** [comment]
Yes issue is solve by other way. Thanks.

On Fri, Nov 20, 2015 at 12:53 AM, Jonathan Eskew <notifications@github.com>
wrote:

> Your comment on the SDK issue
> <https://github.com/aws/aws-sdk-php/issues/829#issuecomment-158153656>
> indicates that this issue is solved? Is that correct, or are you still
> getting an error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-php-laravel/issues/87#issuecomment-158164195>
> .
>



-- 
Thanks & Regards
Piyush Patil


Software Engineer
Sky Id : piyushpatil27
Email Id : piyushpatil027@gmail.com
Mobile No : 09096871715
