### ISSUE TITLE
Setting cloudfront key_pair_id and private_key in config file?

### ISSUE THREAD

**Issue by pulkitjalan** [aws/aws-sdk-php-laravel#88]
How can I set the cloudfront `key_pair_id` and `private_key` configs?

I tried adding:

```php
'cloudfront' => [
    'key_pair_id' => env('CLOUDFRONT_KEY_PAIR_ID'),
    'private_key' => env('CLOUDFRONT_PRIVATE_KEY'),
],
```

in the `config/aws.php` file, but im still getting the `key_pair_id is required` error.

I did try adding it to the request specifically:

```php
$cloudfront->getSignedUrl([
    'url' => $url,
    'expires' => strtotime('1 minute'),
    'key_pair_id' => env('CLOUDFRONT_KEY_PAIR_ID'),
    'private_key' => env('CLOUDFRONT_PRIVATE_KEY'),
]);
```

That does work but its not ideal as i would have to put that in several places.

Thanks.

**Comment by jeskew** [comment]
Hi @pulkitjalan,

There isn't currently a way to set those variables in `config/aws.php`. However, the `getSignedUrl` method of the CloudFront client just creates an instance of `Aws\CloudFront\UrlSigner`, which takes a key pair ID and a private key as constructor arguments. You could expose this as a service in your application like so:
```php
use Aws\CloudFront\UrlSigner;

$this->app->instance(UrlSigner::class, new UrlSigner(
    env('CLOUDFRONT_KEY_PAIR_ID'),
    env('CLOUDFRONT_PRIVATE_KEY')
);
```

Then wherever you need to sign URLs, have the service container inject that instance of `Aws\CloudFront\UrlSigner` and call `getSignedUrl` on it:
```php
use Aws\CloudFront\UrlSigner;

class MySigningService
{
    private $signer;

    public function __construct(UrlSigner $signer)
    {
        $this->signer = $signer;
    }

    public function doStuff()
    {
        // do some stuff
        $signedUrl = $this->signer->getSignedUrl($url, strtotime('1 minute'));
        // do some more stuff
    }
}
```

NB: The `getSignedUrl` method of `Aws\CloudFront\UrlSigner` takes positional arguments, unlike the `getSignedUrl` method of `Aws\CloudFront\CloudFrontClient`, which takes an array.

Hope that helps!

**Comment by pulkitjalan** [comment]
Thanks, I'll do that.
