### ISSUE TITLE
Configure for Lumen

### ISSUE THREAD

**Issue by moh-abk** [aws/aws-sdk-php-laravel#89]
How can I get this to work with `Lumen` as it doesn't have the same files as `Laravel`.
I've copied over my `config/aws.php` file from my `Laravel` project. `Lumen` doesn't have a `config/app.php` file where to put the `alias` and `service provider`. Just a `bootstrap/app.php` file which only has provision for adding `service providers` and I've added there but still no luck. Thanks.

**Comment by GrahamCampbell** [comment]
> Lumen doesn't have a config/app.php file where to put the alias and service provider.

Yes it does. You need to make that file.

**Comment by GrahamCampbell** [comment]
Just go and copy the file from lumen-framework, and put it in the config folder.

**Comment by GrahamCampbell** [comment]
Lumen by default just inherits config from the framework to minimize the number of files in the app.

**Comment by moh-abk** [comment]
I have copied the `config/app.php` file I'm using with my `Laravel` app which has the `alias` and `service provider`

**Comment by GrahamCampbell** [comment]
It should work fine then. Works for me.

**Comment by moh-abk** [comment]
List of what I have done;

Install `aws-sdk-php-laravel` via composer 
Copy over the `config/aws.php` file from my Laravel app 
Copy over the `config/app.php` file from my Laravel app **because Lumen doesn't have this 
Added `use AWS` in my controller

**Comment by moh-abk** [comment]
I'm getting a `Class AWS not found` error
