### ISSUE TITLE
Display Bucket List

### ISSUE THREAD

**Issue by jokerxvier** [aws/aws-sdk-php-laravel#96]
Hi is there an api for displaying all the bucketlist in amazon?

**Comment by jeskew** [comment]
Hi @jokerxvier,

To list all the buckets in your account, you can use the ['ListBuckets` operation](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#listbuckets) like so:
```php
// Create an S3 Client 
$s3Client = App::make('aws')->createClient('s3');
// Call listBuckets with no parameters
$buckets = $s3Client->listBuckets();
```

Hope that helps! Please feel free to reopen if you have any questions or concerns.
