### ISSUE TITLE
Call never ends iotDataPlane

### ISSUE THREAD

**Issue by misiek303** [aws/aws-sdk-php-laravel#97]
Call never ends and never returns from getThingShadow, browser keeps quering..
```
$client = AWS::createClient('iotDataPlane');
$result = $client->getThingShadow([
     'thingName' => $thingName, // REQUIRED
    ]);
```

Also same with 
```
$client->publish([ 'payload' => '{"test": "0"}', 'topic' => "test", 'qos' => 0]);
```
Topic gets published but it never leaves publish method.

What I am doing wrong ?

**Comment by jeskew** [comment]
I'm unable to reproduce with region set to "us-west-2" and version set to "latest". What configuration parameters are you providing to the SDK class?

**Comment by misiek303** [comment]
I use us-east-1 and version = latest. I tried below,

```
$c = new Aws\Sdk(["region" => "us-east-1", "version" => "latest"]);
$iot = $c->createIotDataPlane();
$iot->getThingShadow(['thingName' => 'name']);
```

Same thing, is happening

my configuration
```
<?php

use Aws\Laravel\AwsServiceProvider;

return [

    /*
    |--------------------------------------------------------------------------
    | AWS SDK Configuration
    |--------------------------------------------------------------------------
    |
    | The configuration options set in this file will be passed directly to the
    | `Aws\Sdk` object, from which all client objects are created. The minimum
    | required options are declared here, but the full set of possible options
    | are documented at:
    | http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html
    |
    */

    'credentials' => [
        'key'    => 'XXXXX',
        'secret' => 'XXXXX',
     ],
    'endpoint' => 'https://XXXXXXX.iot.us-east-1.amazonaws.com',
    'scheme'  => 'https',
    'region' => env('AWS_REGION', 'us-east-1'),
    'version' => 'latest',
    'ua_append' => [
        'L5MOD/' . AwsServiceProvider::VERSION,
    ],
];
```

Composer.jsom
```
"require-dev": { ...
        "aws/aws-sdk-php": "^3.15",
        "aws/aws-sdk-php-laravel": "~3.0"
```


I have debugged and found that the code never leaves below line in verndo/aws/aws-sdk-php/src/AwsClient.php line 211
```
return $handler($command);
```

**Comment by jeskew** [comment]
`$handler($command)` is where the request is built and dispatched. Can you make a request to any AWS service (or for that matter send any HTTP message)? If so, could you add `'debug' => true` to your configuration file? That will help pinpoint where the request is hanging.

**Comment by misiek303** [comment]
I was able to create s3 client and return a list of buckets just fine. Or with 'iot' return list of certificates.
I added a debug, but call never ends so never see a debug messages. Is there a way to look at some log files in laravel ?

**Comment by jeskew** [comment]
The SDK has [no custom behavior for the IotDataPlaneClient](https://github.com/aws/aws-sdk-php/blob/master/src/IotDataPlane/IotDataPlaneClient.php#L18), so I don't think this is a bug in the SDK if you can contact S3 and the regular IoT service. Are you able to contact the custom IoT Data endpoint specified in your config file at all?

**Comment by misiek303** [comment]
I tried also this way
```
$iot = App::make('aws')->createClient('iotDataPlane');
$iot->getThingShadow(['thingName' => '']);
```

Is it not a way to get the shadow ?

**Comment by jeskew** [comment]
It is. But I see you're providing a custom endpoint in your config file. Are you able to call `file_get_contents` on that endpoint successfully?

**Comment by misiek303** [comment]
It returns 403 Forbidden

**Comment by misiek303** [comment]
Browser gives me
```
{

    "message": "Missing Authentication Token",
    "traceId": "XXX"

}
```

**Comment by misiek303** [comment]
Looks its not only me
http://codeover.org/posts/33621800/revisions

**Comment by misiek303** [comment]
1. I noticed below url works only from EC2 network ,but gets stuck in my office ( never ends ) even with other networks (  phone )
```
curl http://169.254.169.254/latest/meta-data/
```

2. Using other network ( phone ) requesting GetThingShadow from laravel again, I receive timeout
```
IotDataPlaneException in WrappedHttpHandler.php line 159: Error executing "GetThingShadow" on "http://XXXXX.iot.us-east-1.amazonaws.com/things/XXXX/shadow"; AWS HTTP error: Error creating resource: [message] fopen(http://XXXXX.iot.us-east-1.amazonaws.com/things/XXXXX/shadow): failed to open stream: Connection timed out
[file] /home/xxxx/xxxx/xxxx/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 282
```
Am I missing some rules on the AIM user or something ?

**Comment by jeskew** [comment]
The SDK does not time out connections by default, but this can be configured by setting the [`connect_timeout` HTTP option](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#connect-timeout). I will reach out to the IoT team about connections hanging.

**Comment by misiek303** [comment]
sudo apt-get install php5-curl fixed the issue

**Comment by jeskew** [comment]
Glad to hear that solved the issue. Please feel free to reopen if you have any questions or concerns.
