### ISSUE TITLE
Service Specific Configuration

### ISSUE THREAD

**Issue by nomanurrehman** [aws/aws-sdk-php-laravel#98]
I found this in the docs regarding the configuration file:

```php
// You can override settings for specific services
'Ses' => [
    'region' => 'us-east-1',
]
```

However, I am unable to find any information regarding the services that can be configured in the configuration file plus the keys that can be passed as part of the service's configuration.

I have also tried to look into the source but not much help.

Any help/resource on this would be appreciated.

**Comment by jeskew** [comment]
Sorry for the delay in responding to this. Any SDK service can be configured in the configuration file, and the keys correspond to the namespaces in the AWS SDK (e.g., `Ses` for Amazon Simple Email Service, `Acm` for the Aws Certificate Manager, etc.) No comprehensive list is in this package's README file as it will depend on which version of the SDK you have installed.
